/**
 * @module Pve
 * @category unknown
 * @label unknown
 * @position 1493 / 1990
 * @source esbuild bundle from @iflow-ai/iflow-cli v0.5.19
 * @package iflow-cli-ce (Community Edition)
 * @license Apache-2.0
 *
 * This module was automatically extracted and categorized.
 * The original variable name (Pve) is preserved for compatibility.
 * DO NOT rename this module's variable - it's referenced by other modules.
 */


var Pve = T((Nvc, LKn) => {
  "use strict";
  var IKn = ["GET", "HEAD", "POST"],
    Csa = new Set(IKn),
    Ssa = [101, 204, 205, 304],
    RKn = [301, 302, 303, 307, 308],
    wsa = new Set(RKn),
    kKn = [
      "1",
      "7",
      "9",
      "11",
      "13",
      "15",
      "17",
      "19",
      "20",
      "21",
      "22",
      "23",
      "25",
      "37",
      "42",
      "43",
      "53",
      "69",
      "77",
      "79",
      "87",
      "95",
      "101",
      "102",
      "103",
      "104",
      "109",
      "110",
      "111",
      "113",
      "115",
      "117",
      "119",
      "123",
      "135",
      "137",
      "139",
      "143",
      "161",
      "179",
      "389",
      "427",
      "465",
      "512",
      "513",
      "514",
      "515",
      "526",
      "530",
      "531",
      "532",
      "540",
      "548",
      "554",
      "556",
      "563",
      "587",
      "601",
      "636",
      "989",
      "990",
      "993",
      "995",
      "1719",
      "1720",
      "1723",
      "2049",
      "3659",
      "4045",
      "4190",
      "5060",
      "5061",
      "6000",
      "6566",
      "6665",
      "6666",
      "6667",
      "6668",
      "6669",
      "6679",
      "6697",
      "10080",
    ],
    xsa = new Set(kKn),
    OKn = [
      "no-referrer",
      "no-referrer-when-downgrade",
      "same-origin",
      "origin",
      "strict-origin",
      "origin-when-cross-origin",
      "strict-origin-when-cross-origin",
      "unsafe-url",
    ],
    Tsa = ["", ...OKn],
    Dsa = new Set(OKn),
    Isa = ["follow", "manual", "error"],
    NKn = ["GET", "HEAD", "OPTIONS", "TRACE"],
    Rsa = new Set(NKn),
    ksa = ["navigate", "same-origin", "no-cors", "cors"],
    Osa = ["omit", "same-origin", "include"],
    Nsa = ["default", "no-store", "reload", "no-cache", "force-cache", "only-if-cached"],
    Psa = ["content-encoding", "content-language", "content-location", "content-type", "content-length"],
    Bsa = ["half"],
    PKn = ["CONNECT", "TRACE", "TRACK"],
    Lsa = new Set(PKn),
    BKn = [
      "audio",
      "audioworklet",
      "font",
      "image",
      "manifest",
      "paintworklet",
      "script",
      "style",
      "track",
      "video",
      "xslt",
      "",
    ],
    Msa = new Set(BKn);
  LKn.exports = {
    subresource: BKn,
    forbiddenMethods: PKn,
    requestBodyHeader: Psa,
    referrerPolicy: Tsa,
    requestRedirect: Isa,
    requestMode: ksa,
    requestCredentials: Osa,
    requestCache: Nsa,
    redirectStatus: RKn,
    corsSafeListedMethods: IKn,
    nullBodyStatus: Ssa,
    safeMethods: NKn,
    badPorts: kKn,
    requestDuplex: Bsa,
    subresourceSet: Msa,
    badPortsSet: xsa,
    redirectStatusSet: wsa,
    corsSafeListedMethodsSet: Csa,
    safeMethodsSet: Rsa,
    forbiddenMethodsSet: Lsa,
    referrerPolicyTokens: Dsa,
  };
});