var ProviderRegistry,
  providerRegistryInit = j(() => {
    "use strict";
    const PROVIDERS = [
      // ─── 标准 OpenAI 兼容 ───
      { id:"openai",          name:"OpenAI",               apiType:"openai", baseUrl:"https://api.openai.com/v1",                  docsUrl:"https://platform.openai.com/api-keys",                    defaultModel:"gpt-4.1",         modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"xai",             name:"xAI (Grok)",           apiType:"openai", baseUrl:"https://api.x.ai/v1",                        docsUrl:"https://console.x.ai",                                      defaultModel:"grok-4",          modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"groq",            name:"Groq",                 apiType:"openai", baseUrl:"https://api.groq.com/openai/v1",              docsUrl:"https://console.groq.com/keys",                             defaultModel:"qwen-3-32b",      modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"together",        name:"Together AI",          apiType:"openai", baseUrl:"https://api.together.ai/v1",                  docsUrl:"https://api.together.ai/settings/api-keys",                 defaultModel:"deepseek-ai/DeepSeek-V3", modelsUrl:"/models", thinking:!0, tools:!0, reasoningLevels:null },
      { id:"fireworks",       name:"Fireworks AI",         apiType:"openai", baseUrl:"https://api.fireworks.ai/inference/v1",       docsUrl:"https://fireworks.ai/api-keys",                             defaultModel:"accounts/fireworks/models/deepseek-v3p1", modelsUrl:"/models", thinking:!0, tools:!0, reasoningLevels:null },
      { id:"deepinfra",       name:"Deep Infra",           apiType:"openai", baseUrl:"https://api.deepinfra.com/v1/openai",          docsUrl:"https://deepinfra.com/dash/api_keys",                       defaultModel:"deepseek-ai/DeepSeek-V3", modelsUrl:"/openai/models", thinking:!0, tools:!0, reasoningLevels:null },
      { id:"cerebras",        name:"Cerebras",             apiType:"openai", baseUrl:"https://api.cerebras.ai/v1",                  docsUrl:"https://cloud.cerebras.ai/",                                defaultModel:"llama4-scout-17b", modelsUrl:"/models",     thinking:!1, tools:!0, reasoningLevels:null },
      { id:"baseten",         name:"Baseten",              apiType:"openai", baseUrl:"https://inference.baseten.co/v1",             docsUrl:"https://docs.baseten.co/",                                  defaultModel:"zai-org/GLM-4.7", modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"huggingface",     name:"Hugging Face",         apiType:"openai", baseUrl:"https://router.huggingface.co/v1",            docsUrl:"https://huggingface.co/settings/tokens",                    defaultModel:"openai/gpt-oss-120b", modelsUrl:"/models",   thinking:!0, tools:!0, reasoningLevels:null },
      { id:"venice",          name:"Venice AI",            apiType:"openai", baseUrl:"https://api.venice.ai/api/v1",                docsUrl:"https://venice.ai/api-keys",                                defaultModel:"qwen3-5-9b",      modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"cortecs",         name:"Cortecs",              apiType:"openai", baseUrl:"https://api.cortecs.ai/v1",                  docsUrl:"https://cortecs.ai",                                        defaultModel:"openai/gpt-4.1",  modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"nebius",          name:"Nebius AI",            apiType:"openai", baseUrl:"https://api.studio.nebius.ai/v1",            docsUrl:"https://studio.nebius.ai/",                                 defaultModel:"meta-llama/Llama-3.3-70B", modelsUrl:"/models", thinking:!0, tools:!0, reasoningLevels:null },
      // ─── OpenAI 兼容（有差异）───
      { id:"deepseek",        name:"DeepSeek",             apiType:"openai-ds", baseUrl:"https://api.deepseek.com",               docsUrl:"https://platform.deepseek.com/api_keys",                    defaultModel:"deepseek-chat",   modelsUrl:"/v1/models",  thinking:!0, tools:!0, reasoningLevels:["high","max"], configureRequest:function(r,c){if(c.thinking&&c.thinking!="off"){r.body.thinking={type:"enabled"};r.body.reasoning_effort=c.thinking}else{r.body.thinking={type:"disabled"}}} },
      { id:"zhipu",           name:"智谱 AI (GLM)",         apiType:"openai", baseUrl:"https://open.bigmodel.cn/api/paas/v4",      docsUrl:"https://bigmodel.cn/usercenter/proj-mgmt/apikeys",          defaultModel:"glm-4",          modelsUrl:"/api/paas/v4/modelList", thinking:!0, tools:!0, reasoningLevels:["low","medium","high"], configureRequest:function(r,c){if(c.thinking&&c.thinking!="off"){r.body.chat_template_kwargs={enable_thinking:!0}}else{r.body.chat_template_kwargs={enable_thinking:!1}}} },
      { id:"moonshot",        name:"Moonshot (Kimi)",       apiType:"openai", baseUrl:"https://api.moonshot.cn/v1",                docsUrl:"https://platform.moonshot.cn/console/api-keys",             defaultModel:"kimi-k2.5",       modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"minimax",         name:"MiniMax",              apiType:"openai", baseUrl:"https://api.minimaxi.com/v1",                docsUrl:"https://platform.minimaxi.com/api-keys",                    defaultModel:"MiniMax-M2.7",    modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      // ─── 本地推理 ───
      { id:"ollama",          name:"Ollama (本地)",          apiType:"openai", baseUrl:"http://localhost:11434/v1",                docsUrl:"https://ollama.com",                                        defaultModel:"llama3.2",        modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"ollama-cloud",    name:"Ollama Cloud",          apiType:"openai", baseUrl:"https://cloud.ollama.com/v1",               docsUrl:"https://ollama.com/cloud",                                  defaultModel:"qwen3-coder-480b", modelsUrl:"/models",    thinking:!0, tools:!0, reasoningLevels:null },
      { id:"lmstudio",        name:"LM Studio",             apiType:"openai", baseUrl:"http://localhost:1234/v1",                  docsUrl:"https://lmstudio.ai",                                       defaultModel:"local-model",     modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      { id:"llamacpp",        name:"llama.cpp",             apiType:"openai", baseUrl:"http://localhost:8080/v1",                  docsUrl:"https://github.com/ggerganov/llama.cpp",                    defaultModel:"local-model",     modelsUrl:"/models",     thinking:!0, tools:!0, reasoningLevels:null },
      // ─── 云平台 ───
      { id:"azure-openai",    name:"Azure OpenAI",          apiType:"openai", baseUrl:"https://{resource}.openai.azure.com",         docsUrl:"https://portal.azure.com",                                  defaultModel:"gpt-4o",          modelsUrl:null,          thinking:!0, tools:!0, reasoningLevels:null },
      { id:"nvidia",          name:"NVIDIA NIM",            apiType:"openai", baseUrl:"https://integrate.api.nvidia.com/v1",        docsUrl:"https://build.nvidia.com",                                  defaultModel:"nvidia/llama-3.3-nemotron-super", modelsUrl:"/models", thinking:!0, tools:!0, reasoningLevels:null },
      { id:"ovhcloud",        name:"OVHcloud AI Endpoints", apiType:"openai", baseUrl:"https://endpoints.ai.cloud.ovh.net/v1",      docsUrl:"https://endpoints.ai.cloud.ovh.net",                        defaultModel:"Qwen3-32B",          modelsUrl:"/models",  thinking:!0, tools:!0, reasoningLevels:null },
      { id:"scaleway",        name:"Scaleway",              apiType:"openai", baseUrl:"https://api.scaleway.ai/v1",                 docsUrl:"https://www.scaleway.com/ai/",                              defaultModel:"llama-3.3-70b",    modelsUrl:"/models",   thinking:!0, tools:!0, reasoningLevels:null },
      // ─── 网关/聚合 ───
      { id:"openrouter",      name:"OpenRouter",            apiType:"openai", baseUrl:"https://openrouter.ai/api/v1",               docsUrl:"https://openrouter.ai/keys",                                defaultModel:"openai/gpt-4.1",  modelsUrl:"/api/v1/models", thinking:!0, tools:!0, reasoningLevels:null },
    ];
    ProviderRegistry = { list: PROVIDERS, _ready: !0 };
  });
