var EG_b4 = {},
  eG_b4 = j(() => {
    "use strict";
    function eb(s, start, end) { let i=s.indexOf(start);if(i===-1)return null;i+=start.length;let j=s.indexOf(end,i);return j===-1?null:s.slice(i,j); }
    function st(s) { return s?s.replace(/<[^>]*>/g,'').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim():''; }

    EG_b4.demo_offline = { name:"demo_offline", categories:["general"], shortcut:null, paging:!1, disabled:!0,
      async request(query,params,sq){return params;},
      async response(resp,sq){let results=[];let data=[{value:"first item"},{value:"second item"},{value:"third item"}];for(let i=0;i<data.length;i++){results.push({url:"",title:"Demo Offline Engine Result #"+(i+1),content:"query: "+sq.query+", value: "+data[i].value});}return results;},
    };

    EG_b4.demo_online = { name:"demo_online", categories:["images"], shortcut:null, paging:!0, disabled:!0,
      async request(query,params,sq){let args=new URLSearchParams({q:query,page:sq.pageno||1,fields:"id,title,artist_display,medium_display,image_id,date_display,dimensions,artist_titles",limit:20});params.url="https://api.artic.edu/api/v1/artworks/search?"+args.toString();return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!json||!json.data)return results;for(let r of json.data){if(!r.image_id)continue;results.push({url:"https://artic.edu/artworks/"+r.id,title:r.title+" ("+(r.date_display||"")+") // "+(r.artist_display||""),content:(r.medium_display||"")+" // "+(r.dimensions||""),img_src:"https://www.artic.edu/iiif/2/"+r.image_id+"/full/843,/0/default.jpg",template:"images.html"});}return results;},
    };

    EG_b4.destatis = { name:"destatis", categories:[], shortcut:null, paging:!0,
      async request(query,params,sq){let args=new URLSearchParams({templateQueryString:query,gtp:"474_list%3D"+(sq.pageno||1)});params.url="https://www.destatis.de/SiteGlobals/Forms/Suche/Expertensuche_Formular.html?"+args.toString();return params;},
      async response(resp,sq){let results=[];let parts=resp.text.split('class="c-result');let pageno=sq.pageno||1;for(let i=1;i<parts.length;i++){let block=parts[i];if(pageno>1&&block.indexOf('c-result--recommended')!==-1)continue;let href=eb(block,'href="','"');let title=eb(block,'">','</a>');let content=eb(block,'<p>','</p>');if(!href)continue;let doctype=eb(block,'c-result__doctype','</div>');let dt=doctype?st(eb(doctype,'<p>','</p>')):'';let date=eb(block,'c-result__date','</span>');let d=date?st(date.substring(date.indexOf('>')+1)):'';let meta=[dt,d].filter(Boolean);results.push({url:"https://www.destatis.de/"+href,title:st(title)||"",content:content?st(content):"",metadata:meta.join(', ')});}return results;},
    };

    EG_b4.devicons = { name:"devicons", categories:["images","icons"], shortcut:null, paging:!1,
      async request(query,params,sq){params.url="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.json";params.query=query;return params;},
      async response(resp,sq){let results=[];let qparts=(resp.search_params?.query||sq.query||"").toLowerCase().split(" ").filter(Boolean);let json=resp.json;if(!Array.isArray(json))return results;for(let r of json){let match=qparts.length===0||qparts.some(p=>r.name.indexOf(p)!==-1||(r.altnames||[]).concat(r.tags||[]).some(t=>t.indexOf(p)!==-1));if(!match)continue;for(let imgType of(r.versions?.svg||[])){let src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/"+r.name+"/"+r.name+"-"+imgType+".svg";results.push({template:"images.html",url:src,title:r.name,content:"Base color: "+r.color,img_src:src,img_format:"SVG"});}}return results;},
    };

    EG_b4.dictzone = { name:"dictzone", categories:["general","translate"], shortcut:null, paging:!1, engine_type:"online_dictionary",
      async request(query,params,sq){let from=params.from_lang?.[2]||"english";let to=params.to_lang?.[2]||"german";params.url="https://dictzone.com/"+from+"-"+to+"-dictionary/"+encodeURIComponent(query);return params;},
      async response(resp,sq){let results=[];let html=resp.text;let table=eb(html,'<table','</table>');if(!table)return results;let idx=table.indexOf('id="r"');if(idx===-1)return results;let tbl=table.substring(table.indexOf('>',idx)+1);let rowRe=/<tr>([\s\S]*?)<\/tr>/g;let rm;while((rm=rowRe.exec(tbl))!==null){let cells=[];let tdRe=/<td[^>]*>([\s\S]*?)<\/td>/g;let tm;while((tm=tdRe.exec(rm[1]))!==null)cells.push(tm[1]);if(cells.length!==2)continue;let src=cells[0].replace(/<i>[\s\S]*?<\/i>/g,'').replace(/<span[^>]*>[\s\S]*?<\/span>/g,'');let srcText=st(src);if(!srcText)continue;let translation="";let syns=[];let pRe=/<p[^>]*>([\s\S]*?)<\/p>/g;let pm;let pi=0;while((pm=pRe.exec(cells[1]))!==null){let pt=pm[1].replace(/<i[^>]*>[\s\S]*?<\/i>/g,'').replace(/<button[^>]*>[\s\S]*?<\/button>/g,'');let ptext=st(pt);let smpl=eb(pm[1],'<i class="smpl">','</i>');if(smpl)ptext+=" // "+st(smpl);if(pi===0)translation+=" : "+ptext;else syns.push(ptext);pi++}results.push({url:resp.search_params?.url||"",title:srcText+translation,content:syns.join(', ')||translation});}return results;},
    };

    EG_b4.digbt = { name:"digbt", categories:["videos","music","files"], shortcut:null, paging:!0,
      async request(query,params,sq){params.url="https://digbt.org/search/"+query+"-time-"+(sq.pageno||1);return params;},
      async response(resp,sq){let results=[];let parts=resp.text.split('<td class="x-item">');if(parts.length<2)return results;for(let i=1;i<parts.length;i++){let block=parts[i];let href=eb(block,'<a href="','"');if(!href)continue;let titleSt=eb(block,'<a','</a>');let title=titleSt?st(titleSt.substring(titleSt.lastIndexOf('>')+1)):"";let content=eb(block,'<div class="files">','</div>');let tail=eb(block,'<div class="tail">','</div>');let fdata=tail?tail.split(/<[^>]+>/g).filter(Boolean).map(s=>s.trim()).filter(Boolean):[];let filesize="";if(fdata.length>=6)filesize=fdata[2]+" "+fdata[5];let magnet=eb(block,'href="','"');results.push({url:"https://digbt.org"+href,title:title,content:st(content),filesize:filesize,magnetlink:magnet||"",seed:"N/A",leech:"N/A",template:"torrent.html"});}return results;},
    };

    EG_b4.discourse = { name:"discourse", categories:[], shortcut:null, paging:!0, base_url:null, api_order:"likes", show_avatar:!1, api_key:"", api_username:"",
      async request(query,params,sq){if(query.length<=2)return null;let qarr=[query,"order:"+(EG_b4.discourse.api_order||"likes")];let tr=sq.time_range;if(tr){let ago={day:1,week:7,month:31,year:365};let d=new Date(Date.now()-ago[tr]*86400000);qarr.push("after:"+d.toISOString().split("T")[0]);}let urlBase=EG_b4.discourse.base_url;if(!urlBase)return null;let args=new URLSearchParams({q:qarr.join(" "),page:sq.pageno||1});params.url=urlBase+(EG_b4.discourse.search_endpoint||"/search.json")+"?"+args.toString();params.headers=params.headers||{};params.headers["Accept"]="application/json, text/javascript, */*; q=0.01";params.headers["X-Requested-With"]="XMLHttpRequest";if(EG_b4.discourse.api_key)params.headers["Api-Key"]=EG_b4.discourse.api_key;if(EG_b4.discourse.api_username)params.headers["Api-Username"]=EG_b4.discourse.api_username;return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!json||!(json.topics||json.posts))return results;let topics={};for(let t of json.topics||[])topics[t.id]=t;let base=EG_b4.discourse.base_url||"";let showAv=EG_b4.discourse.show_avatar;for(let post of json.posts||[]){let topic=topics[post.topic_id]||{};let url=base+"/p/"+post.id;let status=topic.closed?"closed":"open";let comments=topic.posts_count||0;let pd=topic.created_at?new Date(topic.created_at):null;let meta=["@"+(post.username||"")];if(comments>1)meta.push("comments: "+comments);if(topic.has_accepted_answer)meta.push("answered");else if(comments>1)meta.push(status);let res={url:url,title:topic.title?topic.title.replace(/&[^;]+;/g,''):"",content:post.blurb?post.blurb.replace(/&[^;]+;/g,''):"",metadata:meta.join(" | "),publishedDate:pd};let avatar=post.avatar_template?post.avatar_template.replace("{size}","96"):"";if(showAv&&avatar)res.thumbnail=base+avatar;results.push(res);}results.push({number_of_results:(json.topics||[]).length});return results;},
    };

    EG_b4.doku = { name:"doku", categories:["general"], shortcut:null, paging:!1, base_url:"http://localhost:8090",
      async request(query,params,sq){let args=new URLSearchParams({id:query});params.url=(EG_b4.doku.base_url||"http://localhost:8090")+"/?do=search&"+args.toString();return params;},
      async response(resp,sq){let results=[];let html=resp.text;let qr=eb(html,'<div class="search_quickresult">','</div>');if(qr){let liRe=/<li>([\s\S]*?)<\/li>/g;let m;while((m=liRe.exec(qr))!==null){let href=eb(m[1],'href="','"');if(!href)continue;let title=m[1].match(/title="([^"]*)"/);results.push({url:(EG_b4.doku.base_url||"http://localhost:8090")+"/"+href,title:title?title[1]:"",content:"",url:""});}}let sr=eb(html,'<dl class="search_results">','</dl>');if(!sr)return results;let dtRe=/<dt>([\s\S]*?)<\/dt>/g;let ddRe=/<dd>([\s\S]*?)<\/dd>/g;let dts=[];let dtm;while((dtm=dtRe.exec(sr))!==null)dts.push(dtm[1]);let ddm;let ddi=0;let curTitle="";let curUrl="";while((ddm=ddRe.exec(sr))!==null){if(ddi<dts.length){let href=eb(dts[ddi],'href="','"');let title=dts[ddi].match(/title="([^"]*)"/);curTitle=title?title[1]:"";curUrl=href?(EG_b4.doku.base_url||"http://localhost:8090")+"/"+href:"";ddi++}let content=st(ddm[1]);if(curUrl)results.push({url:curUrl,title:curTitle,content:content});}return results;},
    };

    EG_b4.duckduckgo_definitions = { name:"duckduckgo_definitions", categories:[], shortcut:null, paging:!1,
      async request(query,params,sq){params.url="https://api.duckduckgo.com/?q="+encodeURIComponent(query)+"&format=json&pretty=0&no_redirect=1&d=1";return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!json)return results;let heading=json.Heading||"";let content=(json.Definition||"")+(json.Abstract||"");let image=json.Image;if(image&&!image.startsWith("http"))image="https://duckduckgo.com"+image;if(json.Answer&&typeof json.Answer==="string"&&json.AnswerType!=="calc"&&json.AnswerType!=="ip"){results.push({title:"Answer",url:json.AbstractURL||"",content:st(json.Answer)});}for(let r of json.Results||[]){if(r.FirstURL&&r.Text)results.push({url:r.FirstURL,title:heading||r.Text,content:r.Text});}for(let r of json.RelatedTopics||[]){if(r.FirstURL&&r.Text&&!r.Text.startsWith("http"))results.push({suggestion:r.Text});else if(r.Topics){for(let t of r.Topics||[]){let txt=t.Text||"";if(!txt.startsWith("http"))results.push({suggestion:txt});}}}if(json.AbstractURL){results.push({url:json.AbstractURL,title:heading,content:content,infobox:heading,img_src:image||undefined});}return results;},
    };

    EG_b4.duckduckgo_extra = { name:"duckduckgo_extra", categories:[], shortcut:null, paging:!0, ddg_category:"", safesearch:!0,
      async request(query,params,sq){if(query.length>=500){params.url=null;return params;}let ua="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0";params.headers=params.headers||{};params.headers["User-Agent"]=ua;let vqd="";try{let r=await fetch("https://duckduckgo.com/?q="+encodeURIComponent(query)+"&iar=images&t=h_",{headers:{"User-Agent":ua}});let txt=await r.text();let idx=txt.indexOf('vqd="');if(idx!==-1){let start=idx+5;let end=txt.indexOf('"',start);if(end!==-1)vqd=txt.substring(start,end);}}catch(e){}params.headers["Accept"]="*/*";params.headers["Referer"]="https://duckduckgo.com/";params.headers["Host"]="duckduckgo.com";let engRegion=params.searxng_locale?.replace("_","-")||"us-en";let engLang=(params.searxng_locale||"en").split("-")[0]||"en";let args={o:"json",q:query,u:"bing",l:engRegion,bpia:"1",vqd:vqd||"",a:"h_"};params.cookies=params.cookies||{};params.cookies["ad"]=engLang;params.cookies["ah"]=engRegion;params.cookies["l"]=engRegion;args["ct"]=params.searxng_locale&&params.searxng_locale!=="all"?params.searxng_locale.split("-")[0].toUpperCase():"EN";if((sq.pageno||1)>1)args["s"]=((sq.pageno||1)-1)*100;let safe=sq.safesearch;if(safe!==undefined){let sc={0:"-2",1:null,2:"1"};let sv=sc[safe];if(sv!==undefined){if(sv!==null)params.cookies["p"]=sv;args["p"]=sv;}}let catMap={images:"i",videos:"v",news:"news"};let cat=EG_b4.duckduckgo_extra.ddg_category||"";let path=catMap[cat]||"i";params.url="https://duckduckgo.com/"+path+".js?"+new URLSearchParams(args).toString();return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!json||!json.results)return results;let cat=EG_b4.duckduckgo_extra.ddg_category||"";for(let r of json.results){if(cat==="images"){results.push({template:"images.html",url:r.url,title:r.title,content:"",thumbnail_src:r.thumbnail,img_src:r.image,resolution:(r.width||"")+" x "+(r.height||""),source:r.source});}else if(cat==="videos"){results.push({template:"videos.html",url:r.content,title:r.title,content:r.description||"",thumbnail:(r.images?.small||r.images?.medium),source:r.provider,length:r.duration,metadata:r.uploader});}else if(cat==="news"){results.push({url:r.url,title:r.title,content:st(r.excerpt||""),source:r.source,publishedDate:r.date?new Date(r.date*1000):null});}}return results;},
    };

    EG_b4.duckduckgo_weather = { name:"duckduckgo_weather", categories:["weather"], shortcut:null, paging:!1,
      async request(query,params,sq){let engLang=params.searxng_locale?.split("_")[0]?.split("-")[0]||"en";let engRegion=params.searxng_locale?.replace("_","-")||"us-en";params.cookies=params.cookies||{};params.cookies["ad"]=engLang;params.cookies["ah"]=engRegion;params.cookies["l"]=engRegion;params.url="https://duckduckgo.com/js/spice/forecast/"+encodeURIComponent(query)+"/"+engLang;return params;},
      async response(resp,sq){let results=[];let txt=resp.text.trim();if(txt==="ddg_spice_forecast();")return results;let nl=txt.indexOf("\n");if(nl===-1)return results;let jsonTxt=txt.substring(nl+1,txt.lastIndexOf("\n")-2);let json;try{json=JSON.parse(jsonTxt);}catch(e){return results;}let current=json.currentWeather;if(!current)return results;let condMap={BlowingDust:"fog",Clear:"clear sky",Cloudy:"cloudy",Foggy:"fog",Haze:"fog",MostlyClear:"clear sky",MostlyCloudy:"partly cloudy",PartlyCloudy:"partly cloudy",Smoky:"fog",Breezy:"partly cloudy",Windy:"partly cloudy",Drizzle:"light rain",HeavyRain:"heavy rain",IsolatedThunderstorms:"rain and thunder",Rain:"rain",SunShowers:"rain",ScatteredThunderstorms:"heavy rain and thunder",StrongStorms:"heavy rain and thunder",Thunderstorms:"rain and thunder",Frigid:"clear sky",Hail:"heavy rain",Hot:"clear sky",Flurries:"light snow",Sleet:"sleet",Snow:"light snow",SunFlurries:"light snow",WintryMix:"sleet",Blizzard:"heavy snow",BlowingSnow:"heavy snow",FreezingDrizzle:"light sleet",FreezingRain:"sleet",HeavySnow:"heavy snow",Hurricane:"rain and thunder",TropicalStorm:"rain and thunder"};let item={temperature:{val:current.temperature,unit:"°C"},condition:condMap[current.conditionCode]||current.conditionCode,feels_like:{val:current.temperatureApparent,unit:"°C"},wind_from:current.windDirection,wind_speed:{val:current.windSpeed,unit:"mi/h"},pressure:{val:current.pressure,unit:"hPa"},humidity:current.humidity*100,cloud_cover:current.cloudCover*100};let forecasts=[];for(let f of json.forecastHourly?.hours||[]){let fitem={temperature:{val:f.temperature,unit:"°C"},condition:condMap[f.conditionCode]||f.conditionCode,feels_like:{val:f.temperatureApparent,unit:"°C"},wind_from:f.windDirection,wind_speed:{val:f.windSpeed,unit:"mi/h"},pressure:{val:f.pressure,unit:"hPa"},humidity:f.humidity*100,cloud_cover:f.cloudCover*100,datetime:f.forecastStart?new Date(f.forecastStart):null};forecasts.push(fitem);}results.push({weather:{current:item,forecasts:forecasts,service:"duckduckgo weather",location:sq.query},title:"Weather for "+sq.query,url:"",content:""});return results;},
    };

    EG_b4.dummy = { name:"dummy", categories:[], shortcut:null, paging:!1,
      async request(query,params,sq){return params;},
      async response(resp,sq){return[];},
    };

    EG_b4.dummy_offline = { name:"dummy_offline", categories:[], shortcut:null, paging:!1,
      async request(query,params,sq){return params;},
      async response(resp,sq){return[{title:"Result",content:"this is what you get",url:""}];},
    };

    EG_b4.fdroid = { name:"fdroid", categories:["files","apps"], shortcut:null, paging:!0,
      async request(query,params,sq){let args=new URLSearchParams({q:query,page:sq.pageno||1,lang:""});params.url="https://search.f-droid.org/?"+args.toString();return params;},
      async response(resp,sq){let results=[];let parts=resp.text.split('<a class="package-header"');for(let i=1;i<parts.length;i++){let block=parts[i];let href=eb(block,'href="','"');let title=eb(block,'class="package-name">','</h4>');let summary=eb(block,'class="package-summary">','</span>');let license=eb(block,'class="package-license">','</span>');let thumb=eb(block,'<img class="package-icon" src="','"');if(!href)continue;let content="";if(summary)content+=st(summary);if(license){if(content)content+=" - ";content+=st(license);}results.push({url:href,title:title?st(title):"",content:content,thumbnail:thumb||""});}return results;},
    };

    EG_b4.findthatmeme = { name:"findthatmeme", categories:["images"], shortcut:null, paging:!0,
      async request(query,params,sq){let offset=((sq.pageno||1)-1)*50;params.url="https://findthatmeme.com/api/v1/search";params.method="POST";params.headers=params.headers||{};params.headers["content-type"]="application/json";params.data=JSON.stringify({search:query,offset:offset});return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!Array.isArray(json))return results;for(let item of json){let img="https://s3.thehackerblog.com/findthatmeme/"+item.image_path;let thumb=item.thumbnail?"https://s3.thehackerblog.com/findthatmeme/thumb/"+item.thumbnail:img;let date=null;if(item.updated_at){let d=item.updated_at.split("T")[0];if(d)date=new Date(d+"T00:00:00");}let fs=item.meme_file_size;let fsize="";if(fs!==undefined&&fs!==null){let units=["B","KB","MB","GB"];let sz=fs;let ui=0;while(sz>=1024&&ui<units.length-1){sz/=1024;ui++}fsize=sz.toFixed(1)+" "+units[ui];}results.push({url:item.source_page_url||"",title:item.source_site||"",img_src:item.type==="IMAGE"?img:thumb,filesize:fsize,publishedDate:date,template:"images.html"});}return results;},
    };

    EG_b4.flickr_noapi = { name:"flickr_noapi", categories:["images"], shortcut:null, paging:!0,
      async request(query,params,sq){let args=new URLSearchParams({text:query});let url="https://www.flickr.com/search?"+args.toString()+"&page="+(sq.pageno||1);let tr=sq.time_range;if(tr){let now=Math.floor(Date.now()/1000);let ranges={day:86400,week:604800,month:2419200,year:31536000};let secs=ranges[tr];if(secs)url+="&min_upload_date="+now+"&max_upload_date="+(now-secs);}params.url=url;return params;},
      async response(resp,sq){let results=[];let m=resp.text.match(/^\s*modelExport:\s*(\{.*\}),$/m);if(!m)return results;let model;try{model=JSON.parse(m[1]);}catch(e){return results;}if(!model||!model.legend||!model.legend[0])return results;let imgSizes=["o","k","h","b","c","z","m","n","t","q","s"];for(let idx of model.legend){if(idx.length!==8)continue;try{let photo=model.main[idx[0]][parseInt(idx[1])][idx[2]][idx[3]][idx[4]][idx[5]][parseInt(idx[6])][idx[7]];if(!photo)continue;let title=photo.title||"";let content=photo.description?st(photo.description):"";let imgSrc=null;let sizeData=null;for(let sz of imgSizes){if(photo.sizes?.data?.[sz]?.data){sizeData=photo.sizes.data[sz].data;break}}if(!sizeData)continue;imgSrc=sizeData.url;let resolution=sizeData.width+" x "+sizeData.height;let thumbSrc=photo.sizes?.data?.n?.data?.url||photo.sizes?.data?.z?.data?.url||imgSrc;let url=photo.ownerNsid?"https://www.flickr.com/photos/"+photo.ownerNsid+"/"+photo.id:imgSrc;results.push({url:url,img_src:imgSrc,thumbnail_src:thumbSrc,source:(photo.username||"")+" @ Flickr",resolution:resolution,template:"images.html",title:title,content:content,author:photo.realname||""});}catch(e){continue}}return results;},
    };

    EG_b4.freesound = { name:"freesound", categories:[], shortcut:null, paging:!0, disabled:!0, api_key:"",
      async request(query,params,sq){let key=EG_b4.freesound.api_key;if(!key)return null;let args=new URLSearchParams({q:query});params.url="https://freesound.org/apiv2/search/text/?query="+args.toString()+"&page="+(sq.pageno||1)+"&fields=name,url,download,created,description,type&token="+key;return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!json||!json.results)return results;for(let r of json.results){results.push({url:r.url,title:r.name,content:r.description?r.description.substring(0,128):"",publishedDate:r.created?new Date(r.created):null,audio_src:r.download||""});}return results;},
    };

    EG_b4.frinkiac = { name:"frinkiac", categories:["images"], shortcut:null, paging:!1,
      async request(query,params,sq){params.url="https://frinkiac.com/api/search?"+new URLSearchParams({q:query}).toString();return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!Array.isArray(json))return results;for(let r of json){let ep=r.Episode;let ts=r.Timestamp;results.push({template:"images.html",url:"https://frinkiac.com/?"+new URLSearchParams({p:"caption",e:ep,t:ts}).toString(),title:ep,content:"",thumbnail_src:"https://frinkiac.com/img/"+ep+"/"+ts+"/medium.jpg",img_src:"https://frinkiac.com/img/"+ep+"/"+ts+".jpg"});}return results;},
    };

    EG_b4.fyyd = { name:"fyyd", categories:[], shortcut:null, paging:!0,
      async request(query,params,sq){let args=new URLSearchParams({term:query,count:10,page:(sq.pageno||1)-1});params.url="https://api.fyyd.de/0.2/search/podcast?"+args.toString();return params;},
      async response(resp,sq){let results=[];let json=resp.json;if(!json||!json.data)return results;for(let r of json.data){let pd=null;if(r.status_since){let parts=r.status_since.split(/[- :]/);if(parts.length===6)pd=new Date(parts[0],parts[1]-1,parts[2],parts[3],parts[4],parts[5]);}results.push({url:r.htmlURL,title:r.title,content:r.description,thumbnail:r.smallImageURL||r.imageURL,publishedDate:pd,metadata:"Rank: "+r.rank+" || "+r.episode_count+" episodes"});}return results;},
    };
  });
