/**
 * @module CLr
 * @category network/grpc
 * @label grpc
 * @position 132 / 1990
 * @source esbuild bundle from @iflow-ai/iflow-cli v0.5.19
 * @package iflow-cli-ce (Community Edition)
 * @license Apache-2.0
 *
 * This module was automatically extracted and categorized.
 * The original variable name (CLr) is preserved for compatibility.
 * DO NOT rename this module's variable - it's referenced by other modules.
 */


var CLr = T((hNe) => {
  "use strict";
  Object.defineProperty(hNe, "__esModule", { value: !0 });
  hNe.VERSION = void 0;
  hNe.VERSION = "2.1.0";
});
function U1(t) {
  let e = {},
    r = t.length;
  for (let n = 0; n < r; n++) {
    let o = t[n];
    o && (e[String(o).toUpperCase().replace(/[-.]/g, "_")] = o);
  }
  return e;
}
var avt = j(() => {});
var SLr,
  wLr,
  xLr,
  TLr,
  DLr,
  ILr,
  RLr,
  kLr,
  OLr,
  NLr,
  PLr,
  BLr,
  LLr,
  MLr,
  FLr,
  ULr,
  $Lr,
  jLr,
  QLr,
  GLr,
  qLr,
  HLr,
  VLr,
  WLr,
  zLr,
  YLr,
  KLr,
  JLr,
  XLr,
  ZLr,
  eMr,
  tMr,
  rMr,
  nMr,
  iMr,
  oMr,
  sMr,
  aMr,
  uMr,
  cMr,
  lMr,
  mMr,
  dMr,
  fMr,
  pMr,
  hMr,
  gMr,
  bMr,
  AMr,
  yMr,
  _Mr,
  EMr,
  vMr,
  CMr,
  SMr,
  wMr,
  xMr,
  TMr,
  DMr,
  IMr,
  RMr,
  kMr,
  OMr,
  NMr,
  PMr,
  BMr,
  LMr,
  MMr,
  FMr,
  UMr,
  $Mr,
  jMr,
  QMr,
  GMr,
  qMr,
  HMr,
  VMr,
  WMr,
  zMr,
  YMr,
  KMr,
  JMr,
  XMr,
  ZMr,
  eFr,
  tFr,
  rFr,
  nFr,
  iFr,
  oFr,
  sFr,
  aFr,
  uFr,
  cFr,
  lFr,
  mFr,
  dFr,
  fFr,
  pFr,
  hFr,
  gFr,
  bFr,
  AFr,
  yFr,
  _Fr,
  EFr,
  vFr,
  CFr,
  SFr,
  wFr,
  xFr,
  TFr,
  DFr,
  IFr,
  RFr,
  kFr,
  OFr,
  NFr,
  PFr,
  BFr,
  LFr,
  MFr,
  FFr,
  UFr,
  $Fr,
  jFr,
  QFr,
  GFr,
  e5o,
  t5o,
  r5o,
  n5o,
  i5o,
  o5o,
  s5o,
  a5o,
  u5o,
  c5o,
  l5o,
  m5o,
  d5o,
  f5o,
  p5o,
  h5o,
  g5o,
  b5o,
  A5o,
  y5o,
  _5o,
  E5o,
  v5o,
  C5o,
  S5o,
  w5o,
  x5o,
  T5o,
  D5o,
  I5o,
  R5o,
  k5o,
  O5o,
  N5o,
  P5o,
  B5o,
  L5o,
  M5o,
  F5o,
  U5o,
  $5o,
  j5o,
  Q5o,
  G5o,
  q5o,
  H5o,
  V5o,
  W5o,
  z5o,
  Y5o,
  K5o,
  J5o,
  X5o,
  Z5o,
  e8o,
  t8o,
  r8o,
  n8o,
  i8o,
  o8o,
  s8o,
  a8o,
  u8o,
  c8o,
  l8o,
  m8o,
  d8o,
  f8o,
  p8o,
  h8o,
  g8o,
  b8o,
  A8o,
  y8o,
  _8o,
  E8o,
  v8o,
  C8o,
  S8o,
  w8o,
  x8o,
  T8o,
  D8o,
  I8o,
  R8o,
  k8o,
  O8o,
  N8o,
  P8o,
  B8o,
  L8o,
  M8o,
  F8o,
  U8o,
  $8o,
  j8o,
  Q8o,
  G8o,
  q8o,
  H8o,
  V8o,
  W8o,
  z8o,
  Y8o,
  K8o,
  J8o,
  X8o,
  Z8o,
  e9o,
  t9o,
  r9o,
  n9o,
  i9o,
  o9o,
  s9o,
  a9o,
  u9o,
  c9o,
  l9o,
  m9o,
  d9o,
  f9o,
  p9o,
  h9o,
  g9o,
  b9o,
  A9o,
  y9o,
  Cte,
  qFr,
  HFr,
  VFr,
  WFr,
  zFr,
  YFr,
  KFr,
  JFr,
  XFr,
  ZFr,
  eUr,
  tUr,
  rUr,
  nUr,
  iUr,
  oUr,
  sUr,
  aUr,
  uUr,
  cUr,
  lUr,
  mUr,
  dUr,
  fUr,
  pUr,
  hUr,
  gUr,
  bUr,
  AUr,
  yUr,
  _Ur,
  EUr,
  vUr,
  CUr,
  SUr,
  wUr,
  xUr,
  TUr,
  DUr,
  IUr,
  RUr,
  kUr,
  OUr,
  NUr,
  PUr,
  BUr,
  LUr,
  _9o,
  E9o,
  v9o,
  C9o,
  S9o,
  w9o,
  x9o,
  T9o,
  D9o,
  I9o,
  R9o,
  k9o,
  O9o,
  N9o,
  P9o,
  B9o,
  L9o,
  M9o,
  F9o,
  U9o,
  $9o,
  j9o,
  Q9o,
  G9o,
  q9o,
  H9o,
  V9o,
  W9o,
  z9o,
  Y9o,
  K9o,
  J9o,
  X9o,
  Z9o,
  e6o,
  t6o,
  r6o,
  n6o,
  i6o,
  o6o,
  s6o,
  a6o,
  u6o,
  c6o,
  l6o,
  m6o,
  d6o,
  f6o,
  MUr,
  FUr,
  UUr,
  $Ur,
  jUr,
  QUr,
  GUr,
  qUr,
  HUr,
  VUr,
  WUr,
  p6o,
  h6o,
  g6o,
  b6o,
  A6o,
  y6o,
  _6o,
  E6o,
  v6o,
  C6o,
  S6o,
  w6o,
  zUr,
  YUr,
  KUr,
  JUr,
  XUr,
  x6o,
  T6o,
  D6o,
  I6o,
  R6o,
  k6o,
  ZUr,
  e$r,
  t$r,
  O6o,
  N6o,
  P6o,
  B6o,
  r$r,
  n$r,
  i$r,
  o$r,
  L6o,
  M6o,
  F6o,
  U6o,
  $6o,
  s$r,
  a$r,
  u$r,
  c$r,
  l$r,
  m$r,
  d$r,
  j6o,
  Q6o,
  G6o,
  q6o,
  H6o,
  V6o,
  W6o,
  z6o,
  f$r,
  p$r,
  h$r,
  g$r,
  b$r,
  Y6o,
  K6o,
  J6o,
  X6o,
  Z6o,
  eyo,
  A$r,
  y$r,
  _$r,
  E$r,
  v$r,
  C$r,
  S$r,
  w$r,
  x$r,
  T$r,
  D$r,
  I$r,
  R$r,
  k$r,
  O$r,
  N$r,
  P$r,
  B$r,
  L$r,
  M$r,
  F$r,
  tyo,
  ryo,
  nyo,
  iyo,
  oyo,
  syo,
  ayo,
  uyo,
  cyo,
  lyo,
  myo,
  dyo,
  fyo,
  pyo,
  hyo,
  gyo,
  byo,
  Ayo,
  yyo,
  _yo,
  Eyo,
  vyo,
  U$r,
  $$r,
  j$r,
  Q$r,
  G$r,
  Cyo,
  Syo,
  wyo,
  xyo,
  Tyo,
  Dyo,
  q$r,
  H$r,
  Iyo,
  Ryo,
  kyo,
  V$r,
  W$r,
  Oyo,
  Nyo,
  Pyo,
  z$r,
  Y$r,
  K$r,
  J$r,
  X$r,
  Z$r,
  ejr,
  tjr,
  rjr,
  njr,
  ijr,
  ojr,
  sjr,
  ajr,
  ujr,
  cjr,
  ljr,
  Byo,
  Lyo,
  Myo,
  Fyo,
  Uyo,
  $yo,
  jyo,
  Qyo,
  Gyo,
  qyo,
  Hyo,
  Vyo,
  Wyo,
  zyo,
  Yyo,
  Kyo,
  Jyo,
  Xyo,
  mjr,
  djr,
  Zyo,
  e_o,
  t_o,
  fjr = j(() => {
    avt();
    ((SLr = "aws.lambda.invoked_arn"),
      (wLr = "db.system"),
      (xLr = "db.connection_string"),
      (TLr = "db.user"),
      (DLr = "db.jdbc.driver_classname"),
      (ILr = "db.name"),
      (RLr = "db.statement"),
      (kLr = "db.operation"),
      (OLr = "db.mssql.instance_name"),
      (NLr = "db.cassandra.keyspace"),
      (PLr = "db.cassandra.page_size"),
      (BLr = "db.cassandra.consistency_level"),
      (LLr = "db.cassandra.table"),
      (MLr = "db.cassandra.idempotence"),
      (FLr = "db.cassandra.speculative_execution_count"),
      (ULr = "db.cassandra.coordinator.id"),
      ($Lr = "db.cassandra.coordinator.dc"),
      (jLr = "db.hbase.namespace"),
      (QLr = "db.redis.database_index"),
      (GLr = "db.mongodb.collection"),
      (qLr = "db.sql.table"),
      (HLr = "exception.type"),
      (VLr = "exception.message"),
      (WLr = "exception.stacktrace"),
      (zLr = "exception.escaped"),
      (YLr = "faas.trigger"),
      (KLr = "faas.execution"),
      (JLr = "faas.document.collection"),
      (XLr = "faas.document.operation"),
      (ZLr = "faas.document.time"),
      (eMr = "faas.document.name"),
      (tMr = "faas.time"),
      (rMr = "faas.cron"),
      (nMr = "faas.coldstart"),
      (iMr = "faas.invoked_name"),
      (oMr = "faas.invoked_provider"),
      (sMr = "faas.invoked_region"),
      (aMr = "net.transport"),
      (uMr = "net.peer.ip"),
      (cMr = "net.peer.port"),
      (lMr = "net.peer.name"),
      (mMr = "net.host.ip"),
      (dMr = "net.host.port"),
      (fMr = "net.host.name"),
      (pMr = "net.host.connection.type"),
      (hMr = "net.host.connection.subtype"),
      (gMr = "net.host.carrier.name"),
      (bMr = "net.host.carrier.mcc"),
      (AMr = "net.host.carrier.mnc"),
      (yMr = "net.host.carrier.icc"),
      (_Mr = "peer.service"),
      (EMr = "enduser.id"),
      (vMr = "enduser.role"),
      (CMr = "enduser.scope"),
      (SMr = "thread.id"),
      (wMr = "thread.name"),
      (xMr = "code.function"),
      (TMr = "code.namespace"),
      (DMr = "code.filepath"),
      (IMr = "code.lineno"),
      (RMr = "http.method"),
      (kMr = "http.url"),
      (OMr = "http.target"),
      (NMr = "http.host"),
      (PMr = "http.scheme"),
      (BMr = "http.status_code"),
      (LMr = "http.flavor"),
      (MMr = "http.user_agent"),
      (FMr = "http.request_content_length"),
      (UMr = "http.request_content_length_uncompressed"),
      ($Mr = "http.response_content_length"),
      (jMr = "http.response_content_length_uncompressed"),
      (QMr = "http.server_name"),
      (GMr = "http.route"),
      (qMr = "http.client_ip"),
      (HMr = "aws.dynamodb.table_names"),
      (VMr = "aws.dynamodb.consumed_capacity"),
      (WMr = "aws.dynamodb.item_collection_metrics"),
      (zMr = "aws.dynamodb.provisioned_read_capacity"),
      (YMr = "aws.dynamodb.provisioned_write_capacity"),
      (KMr = "aws.dynamodb.consistent_read"),
      (JMr = "aws.dynamodb.projection"),
      (XMr = "aws.dynamodb.limit"),
      (ZMr = "aws.dynamodb.attributes_to_get"),
      (eFr = "aws.dynamodb.index_name"),
      (tFr = "aws.dynamodb.select"),
      (rFr = "aws.dynamodb.global_secondary_indexes"),
      (nFr = "aws.dynamodb.local_secondary_indexes"),
      (iFr = "aws.dynamodb.exclusive_start_table"),
      (oFr = "aws.dynamodb.table_count"),
      (sFr = "aws.dynamodb.scan_forward"),
      (aFr = "aws.dynamodb.segment"),
      (uFr = "aws.dynamodb.total_segments"),
      (cFr = "aws.dynamodb.count"),
      (lFr = "aws.dynamodb.scanned_count"),
      (mFr = "aws.dynamodb.attribute_definitions"),
      (dFr = "aws.dynamodb.global_secondary_index_updates"),
      (fFr = "messaging.system"),
      (pFr = "messaging.destination"),
      (hFr = "messaging.destination_kind"),
      (gFr = "messaging.temp_destination"),
      (bFr = "messaging.protocol"),
      (AFr = "messaging.protocol_version"),
      (yFr = "messaging.url"),
      (_Fr = "messaging.message_id"),
      (EFr = "messaging.conversation_id"),
      (vFr = "messaging.message_payload_size_bytes"),
      (CFr = "messaging.message_payload_compressed_size_bytes"),
      (SFr = "messaging.operation"),
      (wFr = "messaging.consumer_id"),
      (xFr = "messaging.rabbitmq.routing_key"),
      (TFr = "messaging.kafka.message_key"),
      (DFr = "messaging.kafka.consumer_group"),
      (IFr = "messaging.kafka.client_id"),
      (RFr = "messaging.kafka.partition"),
      (kFr = "messaging.kafka.tombstone"),
      (OFr = "rpc.system"),
      (NFr = "rpc.service"),
      (PFr = "rpc.method"),
      (BFr = "rpc.grpc.status_code"),
      (LFr = "rpc.jsonrpc.version"),
      (MFr = "rpc.jsonrpc.request_id"),
      (FFr = "rpc.jsonrpc.error_code"),
      (UFr = "rpc.jsonrpc.error_message"),
      ($Fr = "message.type"),
      (jFr = "message.id"),
      (QFr = "message.compressed_size"),
      (GFr = "message.uncompressed_size"),
      (e5o = SLr),
      (t5o = wLr),
      (r5o = xLr),
      (n5o = TLr),
      (i5o = DLr),
      (o5o = ILr),
      (s5o = RLr),
      (a5o = kLr),
      (u5o = OLr),
      (c5o = NLr),
      (l5o = PLr),
      (m5o = BLr),
      (d5o = LLr),
      (f5o = MLr),
      (p5o = FLr),
      (h5o = ULr),
      (g5o = $Lr),
      (b5o = jLr),
      (A5o = QLr),
      (y5o = GLr),
      (_5o = qLr),
      (E5o = HLr),
      (v5o = VLr),
      (C5o = WLr),
      (S5o = zLr),
      (w5o = YLr),
      (x5o = KLr),
      (T5o = JLr),
      (D5o = XLr),
      (I5o = ZLr),
      (R5o = eMr),
      (k5o = tMr),
      (O5o = rMr),
      (N5o = nMr),
      (P5o = iMr),
      (B5o = oMr),
      (L5o = sMr),
      (M5o = aMr),
      (F5o = uMr),
      (U5o = cMr),
      ($5o = lMr),
      (j5o = mMr),
      (Q5o = dMr),
      (G5o = fMr),
      (q5o = pMr),
      (H5o = hMr),
      (V5o = gMr),
      (W5o = bMr),
      (z5o = AMr),
      (Y5o = yMr),
      (K5o = _Mr),
      (J5o = EMr),
      (X5o = vMr),
      (Z5o = CMr),
      (e8o = SMr),
      (t8o = wMr),
      (r8o = xMr),
      (n8o = TMr),
      (i8o = DMr),
      (o8o = IMr),
      (s8o = RMr),
      (a8o = kMr),
      (u8o = OMr),
      (c8o = NMr),
      (l8o = PMr),
      (m8o = BMr),
      (d8o = LMr),
      (f8o = MMr),
      (p8o = FMr),
      (h8o = UMr),
      (g8o = $Mr),
      (b8o = jMr),
      (A8o = QMr),
      (y8o = GMr),
      (_8o = qMr),
      (E8o = HMr),
      (v8o = VMr),
      (C8o = WMr),
      (S8o = zMr),
      (w8o = YMr),
      (x8o = KMr),
      (T8o = JMr),
      (D8o = XMr),
      (I8o = ZMr),
      (R8o = eFr),
      (k8o = tFr),
      (O8o = rFr),
      (N8o = nFr),
      (P8o = iFr),
      (B8o = oFr),
      (L8o = sFr),
      (M8o = aFr),
      (F8o = uFr),
      (U8o = cFr),
      ($8o = lFr),
      (j8o = mFr),
      (Q8o = dFr),
      (G8o = fFr),
      (q8o = pFr),
      (H8o = hFr),
      (V8o = gFr),
      (W8o = bFr),
      (z8o = AFr),
      (Y8o = yFr),
      (K8o = _Fr),
      (J8o = EFr),
      (X8o = vFr),
      (Z8o = CFr),
      (e9o = SFr),
      (t9o = wFr),
      (r9o = xFr),
      (n9o = TFr),
      (i9o = DFr),
      (o9o = IFr),
      (s9o = RFr),
      (a9o = kFr),
      (u9o = OFr),
      (c9o = NFr),
      (l9o = PFr),
      (m9o = BFr),
      (d9o = LFr),
      (f9o = MFr),
      (p9o = FFr),
      (h9o = UFr),
      (g9o = $Fr),
      (b9o = jFr),
      (A9o = QFr),
      (y9o = GFr),
      (Cte = U1([
        SLr,
        wLr,
        xLr,
        TLr,
        DLr,
        ILr,
        RLr,
        kLr,
        OLr,
        NLr,
        PLr,
        BLr,
        LLr,
        MLr,
        FLr,
        ULr,
        $Lr,
        jLr,
        QLr,
        GLr,
        qLr,
        HLr,
        VLr,
        WLr,
        zLr,
        YLr,
        KLr,
        JLr,
        XLr,
        ZLr,
        eMr,
        tMr,
        rMr,
        nMr,
        iMr,
        oMr,
        sMr,
        aMr,
        uMr,
        cMr,
        lMr,
        mMr,
        dMr,
        fMr,
        pMr,
        hMr,
        gMr,
        bMr,
        AMr,
        yMr,
        _Mr,
        EMr,
        vMr,
        CMr,
        SMr,
        wMr,
        xMr,
        TMr,
        DMr,
        IMr,
        RMr,
        kMr,
        OMr,
        NMr,
        PMr,
        BMr,
        LMr,
        MMr,
        FMr,
        UMr,
        $Mr,
        jMr,
        QMr,
        GMr,
        qMr,
        HMr,
        VMr,
        WMr,
        zMr,
        YMr,
        KMr,
        JMr,
        XMr,
        ZMr,
        eFr,
        tFr,
        rFr,
        nFr,
        iFr,
        oFr,
        sFr,
        aFr,
        uFr,
        cFr,
        lFr,
        mFr,
        dFr,
        fFr,
        pFr,
        hFr,
        gFr,
        bFr,
        AFr,
        yFr,
        _Fr,
        EFr,
        vFr,
        CFr,
        SFr,
        wFr,
        xFr,
        TFr,
        DFr,
        IFr,
        RFr,
        kFr,
        OFr,
        NFr,
        PFr,
        BFr,
        LFr,
        MFr,
        FFr,
        UFr,
        $Fr,
        jFr,
        QFr,
        GFr,
      ])),
      (qFr = "other_sql"),
      (HFr = "mssql"),
      (VFr = "mysql"),
      (WFr = "oracle"),
      (zFr = "db2"),
      (YFr = "postgresql"),
      (KFr = "redshift"),
      (JFr = "hive"),
      (XFr = "cloudscape"),
      (ZFr = "hsqldb"),
      (eUr = "progress"),
      (tUr = "maxdb"),
      (rUr = "hanadb"),
      (nUr = "ingres"),
      (iUr = "firstsql"),
      (oUr = "edb"),
      (sUr = "cache"),
      (aUr = "adabas"),
      (uUr = "firebird"),
      (cUr = "derby"),
      (lUr = "filemaker"),
      (mUr = "informix"),
      (dUr = "instantdb"),
      (fUr = "interbase"),
      (pUr = "mariadb"),
      (hUr = "netezza"),
      (gUr = "pervasive"),
      (bUr = "pointbase"),
      (AUr = "sqlite"),
      (yUr = "sybase"),
      (_Ur = "teradata"),
      (EUr = "vertica"),
      (vUr = "h2"),
      (CUr = "coldfusion"),
      (SUr = "cassandra"),
      (wUr = "hbase"),
      (xUr = "mongodb"),
      (TUr = "redis"),
      (DUr = "couchbase"),
      (IUr = "couchdb"),
      (RUr = "cosmosdb"),
      (kUr = "dynamodb"),
      (OUr = "neo4j"),
      (NUr = "geode"),
      (PUr = "elasticsearch"),
      (BUr = "memcached"),
      (LUr = "cockroachdb"),
      (_9o = qFr),
      (E9o = HFr),
      (v9o = VFr),
      (C9o = WFr),
      (S9o = zFr),
      (w9o = YFr),
      (x9o = KFr),
      (T9o = JFr),
      (D9o = XFr),
      (I9o = ZFr),
      (R9o = eUr),
      (k9o = tUr),
      (O9o = rUr),
      (N9o = nUr),
      (P9o = iUr),
      (B9o = oUr),
      (L9o = sUr),
      (M9o = aUr),
      (F9o = uUr),
      (U9o = cUr),
      ($9o = lUr),
      (j9o = mUr),
      (Q9o = dUr),
      (G9o = fUr),
      (q9o = pUr),
      (H9o = hUr),
      (V9o = gUr),
      (W9o = bUr),
      (z9o = AUr),
      (Y9o = yUr),
      (K9o = _Ur),
      (J9o = EUr),
      (X9o = vUr),
      (Z9o = CUr),
      (e6o = SUr),
      (t6o = wUr),
      (r6o = xUr),
      (n6o = TUr),
      (i6o = DUr),
      (o6o = IUr),
      (s6o = RUr),
      (a6o = kUr),
      (u6o = OUr),
      (c6o = NUr),
      (l6o = PUr),
      (m6o = BUr),
      (d6o = LUr),
      (f6o = U1([
        qFr,
        HFr,
        VFr,
        WFr,
        zFr,
        YFr,
        KFr,
        JFr,
        XFr,
        ZFr,
        eUr,
        tUr,
        rUr,
        nUr,
        iUr,
        oUr,
        sUr,
        aUr,
        uUr,
        cUr,
        lUr,
        mUr,
        dUr,
        fUr,
        pUr,
        hUr,
        gUr,
        bUr,
        AUr,
        yUr,
        _Ur,
        EUr,
        vUr,
        CUr,
        SUr,
        wUr,
        xUr,
        TUr,
        DUr,
        IUr,
        RUr,
        kUr,
        OUr,
        NUr,
        PUr,
        BUr,
        LUr,
      ])),
      (MUr = "all"),
      (FUr = "each_quorum"),
      (UUr = "quorum"),
      ($Ur = "local_quorum"),
      (jUr = "one"),
      (QUr = "two"),
      (GUr = "three"),
      (qUr = "local_one"),
      (HUr = "any"),
      (VUr = "serial"),
      (WUr = "local_serial"),
      (p6o = MUr),
      (h6o = FUr),
      (g6o = UUr),
      (b6o = $Ur),
      (A6o = jUr),
      (y6o = QUr),
      (_6o = GUr),
      (E6o = qUr),
      (v6o = HUr),
      (C6o = VUr),
      (S6o = WUr),
      (w6o = U1([MUr, FUr, UUr, $Ur, jUr, QUr, GUr, qUr, HUr, VUr, WUr])),
      (zUr = "datasource"),
      (YUr = "http"),
      (KUr = "pubsub"),
      (JUr = "timer"),
      (XUr = "other"),
      (x6o = zUr),
      (T6o = YUr),
      (D6o = KUr),
      (I6o = JUr),
      (R6o = XUr),
      (k6o = U1([zUr, YUr, KUr, JUr, XUr])),
      (ZUr = "insert"),
      (e$r = "edit"),
      (t$r = "delete"),
      (O6o = ZUr),
      (N6o = e$r),
      (P6o = t$r),
      (B6o = U1([ZUr, e$r, t$r])),
      (r$r = "alibaba_cloud"),
      (n$r = "aws"),
      (i$r = "azure"),
      (o$r = "gcp"),
      (L6o = r$r),
      (M6o = n$r),
      (F6o = i$r),
      (U6o = o$r),
      ($6o = U1([r$r, n$r, i$r, o$r])),
      (s$r = "ip_tcp"),
      (a$r = "ip_udp"),
      (u$r = "ip"),
      (c$r = "unix"),
      (l$r = "pipe"),
      (m$r = "inproc"),
      (d$r = "other"),
      (j6o = s$r),
      (Q6o = a$r),
      (G6o = u$r),
      (q6o = c$r),
      (H6o = l$r),
      (V6o = m$r),
      (W6o = d$r),
      (z6o = U1([s$r, a$r, u$r, c$r, l$r, m$r, d$r])),
      (f$r = "wifi"),
      (p$r = "wired"),
      (h$r = "cell"),
      (g$r = "unavailable"),
      (b$r = "unknown"),
      (Y6o = f$r),
      (K6o = p$r),
      (J6o = h$r),
      (X6o = g$r),
      (Z6o = b$r),
      (eyo = U1([f$r, p$r, h$r, g$r, b$r])),
      (A$r = "gprs"),
      (y$r = "edge"),
      (_$r = "umts"),
      (E$r = "cdma"),
      (v$r = "evdo_0"),
      (C$r = "evdo_a"),
      (S$r = "cdma2000_1xrtt"),
      (w$r = "hsdpa"),
      (x$r = "hsupa"),
      (T$r = "hspa"),
      (D$r = "iden"),
      (I$r = "evdo_b"),
      (R$r = "lte"),
      (k$r = "ehrpd"),
      (O$r = "hspap"),
      (N$r = "gsm"),
      (P$r = "td_scdma"),
      (B$r = "iwlan"),
      (L$r = "nr"),
      (M$r = "nrnsa"),
      (F$r = "lte_ca"),
      (tyo = A$r),
      (ryo = y$r),
      (nyo = _$r),
      (iyo = E$r),
      (oyo = v$r),
      (syo = C$r),
      (ayo = S$r),
      (uyo = w$r),
      (cyo = x$r),
      (lyo = T$r),
      (myo = D$r),
      (dyo = I$r),
      (fyo = R$r),
      (pyo = k$r),
      (hyo = O$r),
      (gyo = N$r),
      (byo = P$r),
      (Ayo = B$r),
      (yyo = L$r),
      (_yo = M$r),
      (Eyo = F$r),
      (vyo = U1([
        A$r,
        y$r,
        _$r,
        E$r,
        v$r,
        C$r,
        S$r,
        w$r,
        x$r,
        T$r,
        D$r,
        I$r,
        R$r,
        k$r,
        O$r,
        N$r,
        P$r,
        B$r,
        L$r,
        M$r,
        F$r,
      ])),
      (U$r = "1.0"),
      ($$r = "1.1"),
      (j$r = "2.0"),
      (Q$r = "SPDY"),
      (G$r = "QUIC"),
      (Cyo = U$r),
      (Syo = $$r),
      (wyo = j$r),
      (xyo = Q$r),
      (Tyo = G$r),
      (Dyo = { HTTP_1_0: U$r, HTTP_1_1: $$r, HTTP_2_0: j$r, SPDY: Q$r, QUIC: G$r }),
      (q$r = "queue"),
      (H$r = "topic"),
      (Iyo = q$r),
      (Ryo = H$r),
      (kyo = U1([q$r, H$r])),
      (V$r = "receive"),
      (W$r = "process"),
      (Oyo = V$r),
      (Nyo = W$r),
      (Pyo = U1([V$r, W$r])),
      (z$r = 0),
      (Y$r = 1),
      (K$r = 2),
      (J$r = 3),
      (X$r = 4),
      (Z$r = 5),
      (ejr = 6),
      (tjr = 7),
      (rjr = 8),
      (njr = 9),
      (ijr = 10),
      (ojr = 11),
      (sjr = 12),
      (ajr = 13),
      (ujr = 14),
      (cjr = 15),
      (ljr = 16),
      (Byo = z$r),
      (Lyo = Y$r),
      (Myo = K$r),
      (Fyo = J$r),
      (Uyo = X$r),
      ($yo = Z$r),
      (jyo = ejr),
      (Qyo = tjr),
      (Gyo = rjr),
      (qyo = njr),
      (Hyo = ijr),
      (Vyo = ojr),
      (Wyo = sjr),
      (zyo = ajr),
      (Yyo = ujr),
      (Kyo = cjr),
      (Jyo = ljr),
      (Xyo = {
        OK: z$r,
        CANCELLED: Y$r,
        UNKNOWN: K$r,
        INVALID_ARGUMENT: J$r,
        DEADLINE_EXCEEDED: X$r,
        NOT_FOUND: Z$r,
        ALREADY_EXISTS: ejr,
        PERMISSION_DENIED: tjr,
        RESOURCE_EXHAUSTED: rjr,
        FAILED_PRECONDITION: njr,
        ABORTED: ijr,
        OUT_OF_RANGE: ojr,
        UNIMPLEMENTED: sjr,
        INTERNAL: ajr,
        UNAVAILABLE: ujr,
        DATA_LOSS: cjr,
        UNAUTHENTICATED: ljr,
      }),
      (mjr = "SENT"),
      (djr = "RECEIVED"),
      (Zyo = mjr),
      (e_o = djr),
      (t_o = U1([mjr, djr])));
  });
var pjr = j(() => {
  fjr();
});
var hjr,
  gjr,
  bjr,
  Ajr,
  yjr,
  _jr,
  Ejr,
  vjr,
  Cjr,
  Sjr,
  wjr,
  xjr,
  Tjr,
  Djr,
  Ijr,
  Rjr,
  kjr,
  Ojr,
  Njr,
  Pjr,
  Bjr,
  Ljr,
  Mjr,
  Fjr,
  Ujr,
  $jr,
  jjr,
  Qjr,
  Gjr,
  qjr,
  Hjr,
  Vjr,
  Wjr,
  zjr,
  Yjr,
  Kjr,
  Jjr,
  Xjr,
  Zjr,
  eQr,
  tQr,
  rQr,
  nQr,
  iQr,
  oQr,
  sQr,
  aQr,
  uQr,
  cQr,
  lQr,
  mQr,
  dQr,
  fQr,
  pQr,
  hQr,
  gQr,
  bQr,
  AQr,
  yQr,
  _Qr,
  EQr,
  vQr,
  CQr,
  SQr,
  wQr,
  xQr,
  TQr,
  DQr,
  IQr,
  RQr,
  kQr,
  OQr,
  NQr,
  PQr,
  BQr,
  LQr,
  MQr,
  FQr,
  UQr,
  $Qr,
  jQr,
  r_o,
  n_o,
  i_o,
  o_o,
  s_o,
  a_o,
  u_o,
  c_o,
  l_o,
  m_o,
  d_o,
  f_o,
  p_o,
  h_o,
  g_o,
  b_o,
  A_o,
  y_o,
  __o,
  E_o,
  v_o,
  C_o,
  S_o,
  w_o,
  x_o,
  T_o,
  D_o,
  I_o,
  R_o,
  k_o,
  O_o,
  N_o,
  P_o,
  B_o,
  L_o,
  M_o,
  F_o,
  U_o,
  $_o,
  j_o,
  Q_o,
  G_o,
  q_o,
  H_o,
  V_o,
  W_o,
  z_o,
  Y_o,
  K_o,
  J_o,
  X_o,
  Z_o,
  eEo,
  tEo,
  rEo,
  nEo,
  iEo,
  oEo,
  sEo,
  aEo,
  uEo,
  cEo,
  lEo,
  mEo,
  dEo,
  fEo,
  pEo,
  hEo,
  gEo,
  bEo,
  AEo,
  yEo,
  _Eo,
  EEo,
  vEo,
  CEo,
  SEo,
  wEo,
  xEo,
  TEo,
  DEo,
  IEo,
  QQr,
  GQr,
  qQr,
  HQr,
  REo,
  kEo,
  OEo,
  NEo,
  PEo,
  VQr,
  WQr,
  zQr,
  YQr,
  KQr,
  JQr,
  XQr,
  ZQr,
  eGr,
  tGr,
  rGr,
  nGr,
  iGr,
  oGr,
  sGr,
  aGr,
  uGr,
  BEo,
  LEo,
  MEo,
  FEo,
  UEo,
  $Eo,
  jEo,
  QEo,
  GEo,
  qEo,
  HEo,
  VEo,
  WEo,
  zEo,
  YEo,
  KEo,
  JEo,
  XEo,
  cGr,
  lGr,
  ZEo,
  evo,
  tvo,
  mGr,
  dGr,
  fGr,
  pGr,
  hGr,
  gGr,
  bGr,
  rvo,
  nvo,
  ivo,
  ovo,
  svo,
  avo,
  uvo,
  cvo,
  AGr,
  yGr,
  _Gr,
  EGr,
  vGr,
  CGr,
  SGr,
  wGr,
  xGr,
  TGr,
  DGr,
  lvo,
  mvo,
  dvo,
  fvo,
  pvo,
  hvo,
  gvo,
  bvo,
  Avo,
  yvo,
  _vo,
  Evo,
  IGr,
  RGr,
  kGr,
  OGr,
  NGr,
  PGr,
  BGr,
  LGr,
  MGr,
  FGr,
  vvo,
  Cvo,
  Svo,
  wvo,
  xvo,
  Tvo,
  Dvo,
  Ivo,
  Rvo,
  kvo,
  Ovo,
  UGr = j(() => {
    avt();
    ((hjr = "cloud.provider"),
      (gjr = "cloud.account.id"),
      (bjr = "cloud.region"),
      (Ajr = "cloud.availability_zone"),
      (yjr = "cloud.platform"),
      (_jr = "aws.ecs.container.arn"),
      (Ejr = "aws.ecs.cluster.arn"),
      (vjr = "aws.ecs.launchtype"),
      (Cjr = "aws.ecs.task.arn"),
      (Sjr = "aws.ecs.task.family"),
      (wjr = "aws.ecs.task.revision"),
      (xjr = "aws.eks.cluster.arn"),
      (Tjr = "aws.log.group.names"),
      (Djr = "aws.log.group.arns"),
      (Ijr = "aws.log.stream.names"),
      (Rjr = "aws.log.stream.arns"),
      (kjr = "container.name"),
      (Ojr = "container.id"),
      (Njr = "container.runtime"),
      (Pjr = "container.image.name"),
      (Bjr = "container.image.tag"),
      (Ljr = "deployment.environment"),
      (Mjr = "device.id"),
      (Fjr = "device.model.identifier"),
      (Ujr = "device.model.name"),
      ($jr = "faas.name"),
      (jjr = "faas.id"),
      (Qjr = "faas.version"),
      (Gjr = "faas.instance"),
      (qjr = "faas.max_memory"),
      (Hjr = "host.id"),
      (Vjr = "host.name"),
      (Wjr = "host.type"),
      (zjr = "host.arch"),
      (Yjr = "host.image.name"),
      (Kjr = "host.image.id"),
      (Jjr = "host.image.version"),
      (Xjr = "k8s.cluster.name"),
      (Zjr = "k8s.node.name"),
      (eQr = "k8s.node.uid"),
      (tQr = "k8s.namespace.name"),
      (rQr = "k8s.pod.uid"),
      (nQr = "k8s.pod.name"),
      (iQr = "k8s.container.name"),
      (oQr = "k8s.replicaset.uid"),
      (sQr = "k8s.replicaset.name"),
      (aQr = "k8s.deployment.uid"),
      (uQr = "k8s.deployment.name"),
      (cQr = "k8s.statefulset.uid"),
      (lQr = "k8s.statefulset.name"),
      (mQr = "k8s.daemonset.uid"),
      (dQr = "k8s.daemonset.name"),
      (fQr = "k8s.job.uid"),
      (pQr = "k8s.job.name"),
      (hQr = "k8s.cronjob.uid"),
      (gQr = "k8s.cronjob.name"),
      (bQr = "os.type"),
      (AQr = "os.description"),
      (yQr = "os.name"),
      (_Qr = "os.version"),
      (EQr = "process.pid"),
      (vQr = "process.executable.name"),
      (CQr = "process.executable.path"),
      (SQr = "process.command"),
      (wQr = "process.command_line"),
      (xQr = "process.command_args"),
      (TQr = "process.owner"),
      (DQr = "process.runtime.name"),
      (IQr = "process.runtime.version"),
      (RQr = "process.runtime.description"),
      (kQr = "service.name"),
      (OQr = "service.namespace"),
      (NQr = "service.instance.id"),
      (PQr = "service.version"),
      (BQr = "telemetry.sdk.name"),
      (LQr = "telemetry.sdk.language"),
      (MQr = "telemetry.sdk.version"),
      (FQr = "telemetry.auto.version"),
      (UQr = "webengine.name"),
      ($Qr = "webengine.version"),
      (jQr = "webengine.description"),
      (r_o = hjr),
      (n_o = gjr),
      (i_o = bjr),
      (o_o = Ajr),
      (s_o = yjr),
      (a_o = _jr),
      (u_o = Ejr),
      (c_o = vjr),
      (l_o = Cjr),
      (m_o = Sjr),
      (d_o = wjr),
      (f_o = xjr),
      (p_o = Tjr),
      (h_o = Djr),
      (g_o = Ijr),
      (b_o = Rjr),
      (A_o = kjr),
      (y_o = Ojr),
      (__o = Njr),
      (E_o = Pjr),
      (v_o = Bjr),
      (C_o = Ljr),
      (S_o = Mjr),
      (w_o = Fjr),
      (x_o = Ujr),
      (T_o = $jr),
      (D_o = jjr),
      (I_o = Qjr),
      (R_o = Gjr),
      (k_o = qjr),
      (O_o = Hjr),
      (N_o = Vjr),
      (P_o = Wjr),
      (B_o = zjr),
      (L_o = Yjr),
      (M_o = Kjr),
      (F_o = Jjr),
      (U_o = Xjr),
      ($_o = Zjr),
      (j_o = eQr),
      (Q_o = tQr),
      (G_o = rQr),
      (q_o = nQr),
      (H_o = iQr),
      (V_o = oQr),
      (W_o = sQr),
      (z_o = aQr),
      (Y_o = uQr),
      (K_o = cQr),
      (J_o = lQr),
      (X_o = mQr),
      (Z_o = dQr),
      (eEo = fQr),
      (tEo = pQr),
      (rEo = hQr),
      (nEo = gQr),
      (iEo = bQr),
      (oEo = AQr),
      (sEo = yQr),
      (aEo = _Qr),
      (uEo = EQr),
      (cEo = vQr),
      (lEo = CQr),
      (mEo = SQr),
      (dEo = wQr),
      (fEo = xQr),
      (pEo = TQr),
      (hEo = DQr),
      (gEo = IQr),
      (bEo = RQr),
      (AEo = kQr),
      (yEo = OQr),
      (_Eo = NQr),
      (EEo = PQr),
      (vEo = BQr),
      (CEo = LQr),
      (SEo = MQr),
      (wEo = FQr),
      (xEo = UQr),
      (TEo = $Qr),
      (DEo = jQr),
      (IEo = U1([
        hjr,
        gjr,
        bjr,
        Ajr,
        yjr,
        _jr,
        Ejr,
        vjr,
        Cjr,
        Sjr,
        wjr,
        xjr,
        Tjr,
        Djr,
        Ijr,
        Rjr,
        kjr,
        Ojr,
        Njr,
        Pjr,
        Bjr,
        Ljr,
        Mjr,
        Fjr,
        Ujr,
        $jr,
        jjr,
        Qjr,
        Gjr,
        qjr,
        Hjr,
        Vjr,
        Wjr,
        zjr,
        Yjr,
        Kjr,
        Jjr,
        Xjr,
        Zjr,
        eQr,
        tQr,
        rQr,
        nQr,
        iQr,
        oQr,
        sQr,
        aQr,
        uQr,
        cQr,
        lQr,
        mQr,
        dQr,
        fQr,
        pQr,
        hQr,
        gQr,
        bQr,
        AQr,
        yQr,
        _Qr,
        EQr,
        vQr,
        CQr,
        SQr,
        wQr,
        xQr,
        TQr,
        DQr,
        IQr,
        RQr,
        kQr,
        OQr,
        NQr,
        PQr,
        BQr,
        LQr,
        MQr,
        FQr,
        UQr,
        $Qr,
        jQr,
      ])),
      (QQr = "alibaba_cloud"),
      (GQr = "aws"),
      (qQr = "azure"),
      (HQr = "gcp"),
      (REo = QQr),
      (kEo = GQr),
      (OEo = qQr),
      (NEo = HQr),
      (PEo = U1([QQr, GQr, qQr, HQr])),
      (VQr = "alibaba_cloud_ecs"),
      (WQr = "alibaba_cloud_fc"),
      (zQr = "aws_ec2"),
      (YQr = "aws_ecs"),
      (KQr = "aws_eks"),
      (JQr = "aws_lambda"),
      (XQr = "aws_elastic_beanstalk"),
      (ZQr = "azure_vm"),
      (eGr = "azure_container_instances"),
      (tGr = "azure_aks"),
      (rGr = "azure_functions"),
      (nGr = "azure_app_service"),
      (iGr = "gcp_compute_engine"),
      (oGr = "gcp_cloud_run"),
      (sGr = "gcp_kubernetes_engine"),
      (aGr = "gcp_cloud_functions"),
      (uGr = "gcp_app_engine"),
      (BEo = VQr),
      (LEo = WQr),
      (MEo = zQr),
      (FEo = YQr),
      (UEo = KQr),
      ($Eo = JQr),
      (jEo = XQr),
      (QEo = ZQr),
      (GEo = eGr),
      (qEo = tGr),
      (HEo = rGr),
      (VEo = nGr),
      (WEo = iGr),
      (zEo = oGr),
      (YEo = sGr),
      (KEo = aGr),
      (JEo = uGr),
      (XEo = U1([VQr, WQr, zQr, YQr, KQr, JQr, XQr, ZQr, eGr, tGr, rGr, nGr, iGr, oGr, sGr, aGr, uGr])),
      (cGr = "ec2"),
      (lGr = "fargate"),
      (ZEo = cGr),
      (evo = lGr),
      (tvo = U1([cGr, lGr])),
      (mGr = "amd64"),
      (dGr = "arm32"),
      (fGr = "arm64"),
      (pGr = "ia64"),
      (hGr = "ppc32"),
      (gGr = "ppc64"),
      (bGr = "x86"),
      (rvo = mGr),
      (nvo = dGr),
      (ivo = fGr),
      (ovo = pGr),
      (svo = hGr),
      (avo = gGr),
      (uvo = bGr),
      (cvo = U1([mGr, dGr, fGr, pGr, hGr, gGr, bGr])),
      (AGr = "windows"),
      (yGr = "linux"),
      (_Gr = "darwin"),
      (EGr = "freebsd"),
      (vGr = "netbsd"),
      (CGr = "openbsd"),
      (SGr = "dragonflybsd"),
      (wGr = "hpux"),
      (xGr = "aix"),
      (TGr = "solaris"),
      (DGr = "z_os"),
      (lvo = AGr),
      (mvo = yGr),
      (dvo = _Gr),
      (fvo = EGr),
      (pvo = vGr),
      (hvo = CGr),
      (gvo = SGr),
      (bvo = wGr),
      (Avo = xGr),
      (yvo = TGr),
      (_vo = DGr),
      (Evo = U1([AGr, yGr, _Gr, EGr, vGr, CGr, SGr, wGr, xGr, TGr, DGr])),
      (IGr = "cpp"),
      (RGr = "dotnet"),
      (kGr = "erlang"),
      (OGr = "go"),
      (NGr = "java"),
      (PGr = "nodejs"),
      (BGr = "php"),
      (LGr = "python"),
      (MGr = "ruby"),
      (FGr = "webjs"),
      (vvo = IGr),
      (Cvo = RGr),
      (Svo = kGr),
      (wvo = OGr),
      (xvo = NGr),
      (Tvo = PGr),
      (Dvo = BGr),
      (Ivo = LGr),
      (Rvo = MGr),
      (kvo = FGr),
      (Ovo = U1([IGr, RGr, kGr, OGr, NGr, PGr, BGr, LGr, MGr, FGr])));
  });
var $Gr = j(() => {
  UGr();
});
var Nvo,
  Pvo,
  Bvo,
  Lvo,
  Mvo,
  Fvo,
  Uvo,
  $vo,
  jvo,
  Qvo,
  Gvo,
  qvo,
  Hvo,
  Vvo,
  Wvo,
  zvo,
  Yvo,
  Kvo,
  Jvo,
  Xvo,
  Zvo,
  eCo,
  tCo,
  rCo,
  nCo,
  iCo,
  oCo,
  sCo,
  aCo,
  uCo,
  cCo,
  lCo,
  mCo,
  dCo,
  fCo,
  pCo,
  hCo,
  gCo,
  bCo,
  ACo,
  yCo,
  _Co,
  A7u,
  y7u,
  ECo,
  vCo,
  CCo,
  SCo,
  wCo,
  xCo,
  TCo,
  DCo,
  ICo,
  RCo,
  kCo,
  _7u,
  OCo,
  NCo,
  PCo,
  BCo,
  E7u,
  LCo,
  MCo,
  FCo,
  UCo,
  $Co,
  jCo,
  QCo,
  GCo,
  qCo,
  HCo,
  VCo,
  WCo,
  zCo,
  YCo,
  KCo,
  v7u,
  JCo,
  XCo,
  ZCo,
  e4o,
  t4o,
  r4o,
  n4o,
  i4o,
  o4o,
  s4o,
  a4o,
  u4o,
  c4o,
  C7u,
  S7u,
  l4o,
  m4o,
  d4o,
  f4o,
  p4o,
  h4o,
  g4o,
  b4o,
  w7u,
  A4o,
  y4o,
  _4o,
  uvt,
  cvt,
  E4o,
  v4o,
  C4o,
  S4o,
  w4o,
  x4o,
  T4o,
  D4o,
  I4o,
  x7u,
  R4o,
  k4o,
  T7u,
  O4o,
  N4o,
  D7u,
  P4o,
  B4o,
  L4o,
  M4o,
  F4o,
  U4o,
  $4o,
  j4o,
  Q4o,
  G4o,
  q4o,
  H4o,
  V4o,
  jGr = j(() => {
    ((Nvo = "aspnetcore.diagnostics.exception.result"),
      (Pvo = "aborted"),
      (Bvo = "handled"),
      (Lvo = "skipped"),
      (Mvo = "unhandled"),
      (Fvo = "aspnetcore.diagnostics.handler.type"),
      (Uvo = "aspnetcore.rate_limiting.policy"),
      ($vo = "aspnetcore.rate_limiting.result"),
      (jvo = "acquired"),
      (Qvo = "endpoint_limiter"),
      (Gvo = "global_limiter"),
      (qvo = "request_canceled"),
      (Hvo = "aspnetcore.request.is_unhandled"),
      (Vvo = "aspnetcore.routing.is_fallback"),
      (Wvo = "aspnetcore.routing.match_status"),
      (zvo = "failure"),
      (Yvo = "success"),
      (Kvo = "aspnetcore.user.is_authenticated"),
      (Jvo = "client.address"),
      (Xvo = "client.port"),
      (Zvo = "code.column.number"),
      (eCo = "code.file.path"),
      (tCo = "code.function.name"),
      (rCo = "code.line.number"),
      (nCo = "code.stacktrace"),
      (iCo = "db.collection.name"),
      (oCo = "db.namespace"),
      (sCo = "db.operation.batch.size"),
      (aCo = "db.operation.name"),
      (uCo = "db.query.summary"),
      (cCo = "db.query.text"),
      (lCo = "db.response.status_code"),
      (mCo = "db.stored_procedure.name"),
      (dCo = "db.system.name"),
      (fCo = "mariadb"),
      (pCo = "microsoft.sql_server"),
      (hCo = "mysql"),
      (gCo = "postgresql"),
      (bCo = "dotnet.gc.heap.generation"),
      (ACo = "gen0"),
      (yCo = "gen1"),
      (_Co = "gen2"),
      (A7u = "loh"),
      (y7u = "poh"),
      (ECo = "error.type"),
      (vCo = "_OTHER"),
      (CCo = "exception.escaped"),
      (SCo = "exception.message"),
      (wCo = "exception.stacktrace"),
      (xCo = "exception.type"),
      (TCo = (t) => `http.request.header.${t}`),
      (DCo = "http.request.method"),
      (ICo = "_OTHER"),
      (RCo = "CONNECT"),
      (kCo = "DELETE"),
      (_7u = "GET"),
      (OCo = "HEAD"),
      (NCo = "OPTIONS"),
      (PCo = "PATCH"),
      (BCo = "POST"),
      (E7u = "PUT"),
      (LCo = "TRACE"),
      (MCo = "http.request.method_original"),
      (FCo = "http.request.resend_count"),
      (UCo = (t) => `http.response.header.${t}`),
      ($Co = "http.response.status_code"),
      (jCo = "http.route"),
      (QCo = "jvm.gc.action"),
      (GCo = "jvm.gc.name"),
      (qCo = "jvm.memory.pool.name"),
      (HCo = "jvm.memory.type"),
      (VCo = "heap"),
      (WCo = "non_heap"),
      (zCo = "jvm.thread.daemon"),
      (YCo = "jvm.thread.state"),
      (KCo = "blocked"),
      (v7u = "new"),
      (JCo = "runnable"),
      (XCo = "terminated"),
      (ZCo = "timed_waiting"),
      (e4o = "waiting"),
      (t4o = "network.local.address"),
      (r4o = "network.local.port"),
      (n4o = "network.peer.address"),
      (i4o = "network.peer.port"),
      (o4o = "network.protocol.name"),
      (s4o = "network.protocol.version"),
      (a4o = "network.transport"),
      (u4o = "pipe"),
      (c4o = "quic"),
      (C7u = "tcp"),
      (S7u = "udp"),
      (l4o = "unix"),
      (m4o = "network.type"),
      (d4o = "ipv4"),
      (f4o = "ipv6"),
      (p4o = "otel.scope.name"),
      (h4o = "otel.scope.version"),
      (g4o = "otel.status_code"),
      (b4o = "ERROR"),
      (w7u = "OK"),
      (A4o = "otel.status_description"),
      (y4o = "server.address"),
      (_4o = "server.port"),
      (uvt = "service.name"),
      (cvt = "service.version"),
      (E4o = "signalr.connection.status"),
      (v4o = "app_shutdown"),
      (C4o = "normal_closure"),
      (S4o = "timeout"),
      (w4o = "signalr.transport"),
      (x4o = "long_polling"),
      (T4o = "server_sent_events"),
      (D4o = "web_sockets"),
      (I4o = "telemetry.sdk.language"),
      (x7u = "cpp"),
      (R4o = "dotnet"),
      (k4o = "erlang"),
      (T7u = "go"),
      (O4o = "java"),
      (N4o = "nodejs"),
      (D7u = "php"),
      (P4o = "python"),
      (B4o = "ruby"),
      (L4o = "rust"),
      (M4o = "swift"),
      (F4o = "webjs"),
      (U4o = "telemetry.sdk.name"),
      ($4o = "telemetry.sdk.version"),
      (j4o = "url.fragment"),
      (Q4o = "url.full"),
      (G4o = "url.path"),
      (q4o = "url.query"),
      (H4o = "url.scheme"),
      (V4o = "user_agent.original"));
  });
var W4o,
  z4o,
  Y4o,
  K4o,
  J4o,
  X4o,
  Z4o,
  eSo,
  tSo,
  rSo,
  nSo,
  iSo,
  oSo,
  sSo,
  aSo,
  uSo,
  cSo,
  lSo,
  mSo,
  dSo,
  fSo,
  pSo,
  hSo,
  gSo,
  bSo,
  ASo,
  ySo,
  _So,
  ESo,
  vSo,
  CSo,
  SSo,
  wSo,
  xSo,
  TSo,
  DSo,
  ISo,
  RSo,
  kSo,
  OSo,
  NSo,
  PSo,
  BSo,
  LSo,
  MSo,
  FSo,
  USo,
  $So,
  jSo,
  QSo,
  GSo,
  QGr = j(() => {
    ((W4o = "aspnetcore.diagnostics.exceptions"),
      (z4o = "aspnetcore.rate_limiting.active_request_leases"),
      (Y4o = "aspnetcore.rate_limiting.queued_requests"),
      (K4o = "aspnetcore.rate_limiting.request.time_in_queue"),
      (J4o = "aspnetcore.rate_limiting.request_lease.duration"),
      (X4o = "aspnetcore.rate_limiting.requests"),
      (Z4o = "aspnetcore.routing.match_attempts"),
      (eSo = "db.client.operation.duration"),
      (tSo = "dotnet.assembly.count"),
      (rSo = "dotnet.exceptions"),
      (nSo = "dotnet.gc.collections"),
      (iSo = "dotnet.gc.heap.total_allocated"),
      (oSo = "dotnet.gc.last_collection.heap.fragmentation.size"),
      (sSo = "dotnet.gc.last_collection.heap.size"),
      (aSo = "dotnet.gc.last_collection.memory.committed_size"),
      (uSo = "dotnet.gc.pause.time"),
      (cSo = "dotnet.jit.compilation.time"),
      (lSo = "dotnet.jit.compiled_il.size"),
      (mSo = "dotnet.jit.compiled_methods"),
      (dSo = "dotnet.monitor.lock_contentions"),
      (fSo = "dotnet.process.cpu.count"),
      (pSo = "dotnet.process.cpu.time"),
      (hSo = "dotnet.process.memory.working_set"),
      (gSo = "dotnet.thread_pool.queue.length"),
      (bSo = "dotnet.thread_pool.thread.count"),
      (ASo = "dotnet.thread_pool.work_item.count"),
      (ySo = "dotnet.timer.count"),
      (_So = "http.client.request.duration"),
      (ESo = "http.server.request.duration"),
      (vSo = "jvm.class.count"),
      (CSo = "jvm.class.loaded"),
      (SSo = "jvm.class.unloaded"),
      (wSo = "jvm.cpu.count"),
      (xSo = "jvm.cpu.recent_utilization"),
      (TSo = "jvm.cpu.time"),
      (DSo = "jvm.gc.duration"),
      (ISo = "jvm.memory.committed"),
      (RSo = "jvm.memory.limit"),
      (kSo = "jvm.memory.used"),
      (OSo = "jvm.memory.used_after_last_gc"),
      (NSo = "jvm.thread.count"),
      (PSo = "kestrel.active_connections"),
      (BSo = "kestrel.active_tls_handshakes"),
      (LSo = "kestrel.connection.duration"),
      (MSo = "kestrel.queued_connections"),
      (FSo = "kestrel.queued_requests"),
      (USo = "kestrel.rejected_connections"),
      ($So = "kestrel.tls_handshake.duration"),
      (jSo = "kestrel.upgraded_connections"),
      (QSo = "signalr.server.active_connections"),
      (GSo = "signalr.server.connection.duration"));
  });
var qSo,
  GGr = j(() => {
    qSo = "exception";
  });
var Ih = {};
Wi(Ih, {
  ASPNETCORE_DIAGNOSTICS_EXCEPTION_RESULT_VALUE_ABORTED: () => Pvo,
  ASPNETCORE_DIAGNOSTICS_EXCEPTION_RESULT_VALUE_HANDLED: () => Bvo,
  ASPNETCORE_DIAGNOSTICS_EXCEPTION_RESULT_VALUE_SKIPPED: () => Lvo,
  ASPNETCORE_DIAGNOSTICS_EXCEPTION_RESULT_VALUE_UNHANDLED: () => Mvo,
  ASPNETCORE_RATE_LIMITING_RESULT_VALUE_ACQUIRED: () => jvo,
  ASPNETCORE_RATE_LIMITING_RESULT_VALUE_ENDPOINT_LIMITER: () => Qvo,
  ASPNETCORE_RATE_LIMITING_RESULT_VALUE_GLOBAL_LIMITER: () => Gvo,
  ASPNETCORE_RATE_LIMITING_RESULT_VALUE_REQUEST_CANCELED: () => qvo,
  ASPNETCORE_ROUTING_MATCH_STATUS_VALUE_FAILURE: () => zvo,
  ASPNETCORE_ROUTING_MATCH_STATUS_VALUE_SUCCESS: () => Yvo,
  ATTR_ASPNETCORE_DIAGNOSTICS_EXCEPTION_RESULT: () => Nvo,
  ATTR_ASPNETCORE_DIAGNOSTICS_HANDLER_TYPE: () => Fvo,
  ATTR_ASPNETCORE_RATE_LIMITING_POLICY: () => Uvo,
  ATTR_ASPNETCORE_RATE_LIMITING_RESULT: () => $vo,
  ATTR_ASPNETCORE_REQUEST_IS_UNHANDLED: () => Hvo,
  ATTR_ASPNETCORE_ROUTING_IS_FALLBACK: () => Vvo,
  ATTR_ASPNETCORE_ROUTING_MATCH_STATUS: () => Wvo,
  ATTR_ASPNETCORE_USER_IS_AUTHENTICATED: () => Kvo,
  ATTR_CLIENT_ADDRESS: () => Jvo,
  ATTR_CLIENT_PORT: () => Xvo,
  ATTR_CODE_COLUMN_NUMBER: () => Zvo,
  ATTR_CODE_FILE_PATH: () => eCo,
  ATTR_CODE_FUNCTION_NAME: () => tCo,
  ATTR_CODE_LINE_NUMBER: () => rCo,
  ATTR_CODE_STACKTRACE: () => nCo,
  ATTR_DB_COLLECTION_NAME: () => iCo,
  ATTR_DB_NAMESPACE: () => oCo,
  ATTR_DB_OPERATION_BATCH_SIZE: () => sCo,
  ATTR_DB_OPERATION_NAME: () => aCo,
  ATTR_DB_QUERY_SUMMARY: () => uCo,
  ATTR_DB_QUERY_TEXT: () => cCo,
  ATTR_DB_RESPONSE_STATUS_CODE: () => lCo,
  ATTR_DB_STORED_PROCEDURE_NAME: () => mCo,
  ATTR_DB_SYSTEM_NAME: () => dCo,
  ATTR_DOTNET_GC_HEAP_GENERATION: () => bCo,
  ATTR_ERROR_TYPE: () => ECo,
  ATTR_EXCEPTION_ESCAPED: () => CCo,
  ATTR_EXCEPTION_MESSAGE: () => SCo,
  ATTR_EXCEPTION_STACKTRACE: () => wCo,
  ATTR_EXCEPTION_TYPE: () => xCo,
  ATTR_HTTP_REQUEST_HEADER: () => TCo,
  ATTR_HTTP_REQUEST_METHOD: () => DCo,
  ATTR_HTTP_REQUEST_METHOD_ORIGINAL: () => MCo,
  ATTR_HTTP_REQUEST_RESEND_COUNT: () => FCo,
  ATTR_HTTP_RESPONSE_HEADER: () => UCo,
  ATTR_HTTP_RESPONSE_STATUS_CODE: () => $Co,
  ATTR_HTTP_ROUTE: () => jCo,
  ATTR_JVM_GC_ACTION: () => QCo,
  ATTR_JVM_GC_NAME: () => GCo,
  ATTR_JVM_MEMORY_POOL_NAME: () => qCo,
  ATTR_JVM_MEMORY_TYPE: () => HCo,
  ATTR_JVM_THREAD_DAEMON: () => zCo,
  ATTR_JVM_THREAD_STATE: () => YCo,
  ATTR_NETWORK_LOCAL_ADDRESS: () => t4o,
  ATTR_NETWORK_LOCAL_PORT: () => r4o,
  ATTR_NETWORK_PEER_ADDRESS: () => n4o,
  ATTR_NETWORK_PEER_PORT: () => i4o,
  ATTR_NETWORK_PROTOCOL_NAME: () => o4o,
  ATTR_NETWORK_PROTOCOL_VERSION: () => s4o,
  ATTR_NETWORK_TRANSPORT: () => a4o,
  ATTR_NETWORK_TYPE: () => m4o,
  ATTR_OTEL_SCOPE_NAME: () => p4o,
  ATTR_OTEL_SCOPE_VERSION: () => h4o,
  ATTR_OTEL_STATUS_CODE: () => g4o,
  ATTR_OTEL_STATUS_DESCRIPTION: () => A4o,
  ATTR_SERVER_ADDRESS: () => y4o,
  ATTR_SERVER_PORT: () => _4o,
  ATTR_SERVICE_NAME: () => uvt,
  ATTR_SERVICE_VERSION: () => cvt,
  ATTR_SIGNALR_CONNECTION_STATUS: () => E4o,
  ATTR_SIGNALR_TRANSPORT: () => w4o,
  ATTR_TELEMETRY_SDK_LANGUAGE: () => I4o,
  ATTR_TELEMETRY_SDK_NAME: () => U4o,
  ATTR_TELEMETRY_SDK_VERSION: () => $4o,
  ATTR_URL_FRAGMENT: () => j4o,
  ATTR_URL_FULL: () => Q4o,
  ATTR_URL_PATH: () => G4o,
  ATTR_URL_QUERY: () => q4o,
  ATTR_URL_SCHEME: () => H4o,
  ATTR_USER_AGENT_ORIGINAL: () => V4o,
  AWSECSLAUNCHTYPEVALUES_EC2: () => ZEo,
  AWSECSLAUNCHTYPEVALUES_FARGATE: () => evo,
  AwsEcsLaunchtypeValues: () => tvo,
  CLOUDPLATFORMVALUES_ALIBABA_CLOUD_ECS: () => BEo,
  CLOUDPLATFORMVALUES_ALIBABA_CLOUD_FC: () => LEo,
  CLOUDPLATFORMVALUES_AWS_EC2: () => MEo,
  CLOUDPLATFORMVALUES_AWS_ECS: () => FEo,
  CLOUDPLATFORMVALUES_AWS_EKS: () => UEo,
  CLOUDPLATFORMVALUES_AWS_ELASTIC_BEANSTALK: () => jEo,
  CLOUDPLATFORMVALUES_AWS_LAMBDA: () => $Eo,
  CLOUDPLATFORMVALUES_AZURE_AKS: () => qEo,
  CLOUDPLATFORMVALUES_AZURE_APP_SERVICE: () => VEo,
  CLOUDPLATFORMVALUES_AZURE_CONTAINER_INSTANCES: () => GEo,
  CLOUDPLATFORMVALUES_AZURE_FUNCTIONS: () => HEo,
  CLOUDPLATFORMVALUES_AZURE_VM: () => QEo,
  CLOUDPLATFORMVALUES_GCP_APP_ENGINE: () => JEo,
  CLOUDPLATFORMVALUES_GCP_CLOUD_FUNCTIONS: () => KEo,
  CLOUDPLATFORMVALUES_GCP_CLOUD_RUN: () => zEo,
  CLOUDPLATFORMVALUES_GCP_COMPUTE_ENGINE: () => WEo,
  CLOUDPLATFORMVALUES_GCP_KUBERNETES_ENGINE: () => YEo,
  CLOUDPROVIDERVALUES_ALIBABA_CLOUD: () => REo,
  CLOUDPROVIDERVALUES_AWS: () => kEo,
  CLOUDPROVIDERVALUES_AZURE: () => OEo,
  CLOUDPROVIDERVALUES_GCP: () => NEo,
  CloudPlatformValues: () => XEo,
  CloudProviderValues: () => PEo,
  DBCASSANDRACONSISTENCYLEVELVALUES_ALL: () => p6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_ANY: () => v6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_EACH_QUORUM: () => h6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_ONE: () => E6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_QUORUM: () => b6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_SERIAL: () => S6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_ONE: () => A6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_QUORUM: () => g6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_SERIAL: () => C6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_THREE: () => _6o,
  DBCASSANDRACONSISTENCYLEVELVALUES_TWO: () => y6o,
  DBSYSTEMVALUES_ADABAS: () => M9o,
  DBSYSTEMVALUES_CACHE: () => L9o,
  DBSYSTEMVALUES_CASSANDRA: () => e6o,
  DBSYSTEMVALUES_CLOUDSCAPE: () => D9o,
  DBSYSTEMVALUES_COCKROACHDB: () => d6o,
  DBSYSTEMVALUES_COLDFUSION: () => Z9o,
  DBSYSTEMVALUES_COSMOSDB: () => s6o,
  DBSYSTEMVALUES_COUCHBASE: () => i6o,
  DBSYSTEMVALUES_COUCHDB: () => o6o,
  DBSYSTEMVALUES_DB2: () => S9o,
  DBSYSTEMVALUES_DERBY: () => U9o,
  DBSYSTEMVALUES_DYNAMODB: () => a6o,
  DBSYSTEMVALUES_EDB: () => B9o,
  DBSYSTEMVALUES_ELASTICSEARCH: () => l6o,
  DBSYSTEMVALUES_FILEMAKER: () => $9o,
  DBSYSTEMVALUES_FIREBIRD: () => F9o,
  DBSYSTEMVALUES_FIRSTSQL: () => P9o,
  DBSYSTEMVALUES_GEODE: () => c6o,
  DBSYSTEMVALUES_H2: () => X9o,
  DBSYSTEMVALUES_HANADB: () => O9o,
  DBSYSTEMVALUES_HBASE: () => t6o,
  DBSYSTEMVALUES_HIVE: () => T9o,
  DBSYSTEMVALUES_HSQLDB: () => I9o,
  DBSYSTEMVALUES_INFORMIX: () => j9o,
  DBSYSTEMVALUES_INGRES: () => N9o,
  DBSYSTEMVALUES_INSTANTDB: () => Q9o,
  DBSYSTEMVALUES_INTERBASE: () => G9o,
  DBSYSTEMVALUES_MARIADB: () => q9o,
  DBSYSTEMVALUES_MAXDB: () => k9o,
  DBSYSTEMVALUES_MEMCACHED: () => m6o,
  DBSYSTEMVALUES_MONGODB: () => r6o,
  DBSYSTEMVALUES_MSSQL: () => E9o,
  DBSYSTEMVALUES_MYSQL: () => v9o,
  DBSYSTEMVALUES_NEO4J: () => u6o,
  DBSYSTEMVALUES_NETEZZA: () => H9o,
  DBSYSTEMVALUES_ORACLE: () => C9o,
  DBSYSTEMVALUES_OTHER_SQL: () => _9o,
  DBSYSTEMVALUES_PERVASIVE: () => V9o,
  DBSYSTEMVALUES_POINTBASE: () => W9o,
  DBSYSTEMVALUES_POSTGRESQL: () => w9o,
  DBSYSTEMVALUES_PROGRESS: () => R9o,
  DBSYSTEMVALUES_REDIS: () => n6o,
  DBSYSTEMVALUES_REDSHIFT: () => x9o,
  DBSYSTEMVALUES_SQLITE: () => z9o,
  DBSYSTEMVALUES_SYBASE: () => Y9o,
  DBSYSTEMVALUES_TERADATA: () => K9o,
  DBSYSTEMVALUES_VERTICA: () => J9o,
  DB_SYSTEM_NAME_VALUE_MARIADB: () => fCo,
  DB_SYSTEM_NAME_VALUE_MICROSOFT_SQL_SERVER: () => pCo,
  DB_SYSTEM_NAME_VALUE_MYSQL: () => hCo,
  DB_SYSTEM_NAME_VALUE_POSTGRESQL: () => gCo,
  DOTNET_GC_HEAP_GENERATION_VALUE_GEN0: () => ACo,
  DOTNET_GC_HEAP_GENERATION_VALUE_GEN1: () => yCo,
  DOTNET_GC_HEAP_GENERATION_VALUE_GEN2: () => _Co,
  DOTNET_GC_HEAP_GENERATION_VALUE_LOH: () => A7u,
  DOTNET_GC_HEAP_GENERATION_VALUE_POH: () => y7u,
  DbCassandraConsistencyLevelValues: () => w6o,
  DbSystemValues: () => f6o,
  ERROR_TYPE_VALUE_OTHER: () => vCo,
  EVENT_EXCEPTION: () => qSo,
  FAASDOCUMENTOPERATIONVALUES_DELETE: () => P6o,
  FAASDOCUMENTOPERATIONVALUES_EDIT: () => N6o,
  FAASDOCUMENTOPERATIONVALUES_INSERT: () => O6o,
  FAASINVOKEDPROVIDERVALUES_ALIBABA_CLOUD: () => L6o,
  FAASINVOKEDPROVIDERVALUES_AWS: () => M6o,
  FAASINVOKEDPROVIDERVALUES_AZURE: () => F6o,
  FAASINVOKEDPROVIDERVALUES_GCP: () => U6o,
  FAASTRIGGERVALUES_DATASOURCE: () => x6o,
  FAASTRIGGERVALUES_HTTP: () => T6o,
  FAASTRIGGERVALUES_OTHER: () => R6o,
  FAASTRIGGERVALUES_PUBSUB: () => D6o,
  FAASTRIGGERVALUES_TIMER: () => I6o,
  FaasDocumentOperationValues: () => B6o,
  FaasInvokedProviderValues: () => $6o,
  FaasTriggerValues: () => k6o,
  HOSTARCHVALUES_AMD64: () => rvo,
  HOSTARCHVALUES_ARM32: () => nvo,
  HOSTARCHVALUES_ARM64: () => ivo,
  HOSTARCHVALUES_IA64: () => ovo,
  HOSTARCHVALUES_PPC32: () => svo,
  HOSTARCHVALUES_PPC64: () => avo,
  HOSTARCHVALUES_X86: () => uvo,
  HTTPFLAVORVALUES_HTTP_1_0: () => Cyo,
  HTTPFLAVORVALUES_HTTP_1_1: () => Syo,
  HTTPFLAVORVALUES_HTTP_2_0: () => wyo,
  HTTPFLAVORVALUES_QUIC: () => Tyo,
  HTTPFLAVORVALUES_SPDY: () => xyo,
  HTTP_REQUEST_METHOD_VALUE_CONNECT: () => RCo,
  HTTP_REQUEST_METHOD_VALUE_DELETE: () => kCo,
  HTTP_REQUEST_METHOD_VALUE_GET: () => _7u,
  HTTP_REQUEST_METHOD_VALUE_HEAD: () => OCo,
  HTTP_REQUEST_METHOD_VALUE_OPTIONS: () => NCo,
  HTTP_REQUEST_METHOD_VALUE_OTHER: () => ICo,
  HTTP_REQUEST_METHOD_VALUE_PATCH: () => PCo,
  HTTP_REQUEST_METHOD_VALUE_POST: () => BCo,
  HTTP_REQUEST_METHOD_VALUE_PUT: () => E7u,
  HTTP_REQUEST_METHOD_VALUE_TRACE: () => LCo,
  HostArchValues: () => cvo,
  HttpFlavorValues: () => Dyo,
  JVM_MEMORY_TYPE_VALUE_HEAP: () => VCo,
  JVM_MEMORY_TYPE_VALUE_NON_HEAP: () => WCo,
  JVM_THREAD_STATE_VALUE_BLOCKED: () => KCo,
  JVM_THREAD_STATE_VALUE_NEW: () => v7u,
  JVM_THREAD_STATE_VALUE_RUNNABLE: () => JCo,
  JVM_THREAD_STATE_VALUE_TERMINATED: () => XCo,
  JVM_THREAD_STATE_VALUE_TIMED_WAITING: () => ZCo,
  JVM_THREAD_STATE_VALUE_WAITING: () => e4o,
  MESSAGETYPEVALUES_RECEIVED: () => e_o,
  MESSAGETYPEVALUES_SENT: () => Zyo,
  MESSAGINGDESTINATIONKINDVALUES_QUEUE: () => Iyo,
  MESSAGINGDESTINATIONKINDVALUES_TOPIC: () => Ryo,
  MESSAGINGOPERATIONVALUES_PROCESS: () => Nyo,
  MESSAGINGOPERATIONVALUES_RECEIVE: () => Oyo,
  METRIC_ASPNETCORE_DIAGNOSTICS_EXCEPTIONS: () => W4o,
  METRIC_ASPNETCORE_RATE_LIMITING_ACTIVE_REQUEST_LEASES: () => z4o,
  METRIC_ASPNETCORE_RATE_LIMITING_QUEUED_REQUESTS: () => Y4o,
  METRIC_ASPNETCORE_RATE_LIMITING_REQUESTS: () => X4o,
  METRIC_ASPNETCORE_RATE_LIMITING_REQUEST_LEASE_DURATION: () => J4o,
  METRIC_ASPNETCORE_RATE_LIMITING_REQUEST_TIME_IN_QUEUE: () => K4o,
  METRIC_ASPNETCORE_ROUTING_MATCH_ATTEMPTS: () => Z4o,
  METRIC_DB_CLIENT_OPERATION_DURATION: () => eSo,
  METRIC_DOTNET_ASSEMBLY_COUNT: () => tSo,
  METRIC_DOTNET_EXCEPTIONS: () => rSo,
  METRIC_DOTNET_GC_COLLECTIONS: () => nSo,
  METRIC_DOTNET_GC_HEAP_TOTAL_ALLOCATED: () => iSo,
  METRIC_DOTNET_GC_LAST_COLLECTION_HEAP_FRAGMENTATION_SIZE: () => oSo,
  METRIC_DOTNET_GC_LAST_COLLECTION_HEAP_SIZE: () => sSo,
  METRIC_DOTNET_GC_LAST_COLLECTION_MEMORY_COMMITTED_SIZE: () => aSo,
  METRIC_DOTNET_GC_PAUSE_TIME: () => uSo,
  METRIC_DOTNET_JIT_COMPILATION_TIME: () => cSo,
  METRIC_DOTNET_JIT_COMPILED_IL_SIZE: () => lSo,
  METRIC_DOTNET_JIT_COMPILED_METHODS: () => mSo,
  METRIC_DOTNET_MONITOR_LOCK_CONTENTIONS: () => dSo,
  METRIC_DOTNET_PROCESS_CPU_COUNT: () => fSo,
  METRIC_DOTNET_PROCESS_CPU_TIME: () => pSo,
  METRIC_DOTNET_PROCESS_MEMORY_WORKING_SET: () => hSo,
  METRIC_DOTNET_THREAD_POOL_QUEUE_LENGTH: () => gSo,
  METRIC_DOTNET_THREAD_POOL_THREAD_COUNT: () => bSo,
  METRIC_DOTNET_THREAD_POOL_WORK_ITEM_COUNT: () => ASo,
  METRIC_DOTNET_TIMER_COUNT: () => ySo,
  METRIC_HTTP_CLIENT_REQUEST_DURATION: () => _So,
  METRIC_HTTP_SERVER_REQUEST_DURATION: () => ESo,
  METRIC_JVM_CLASS_COUNT: () => vSo,
  METRIC_JVM_CLASS_LOADED: () => CSo,
  METRIC_JVM_CLASS_UNLOADED: () => SSo,
  METRIC_JVM_CPU_COUNT: () => wSo,
  METRIC_JVM_CPU_RECENT_UTILIZATION: () => xSo,
  METRIC_JVM_CPU_TIME: () => TSo,
  METRIC_JVM_GC_DURATION: () => DSo,
  METRIC_JVM_MEMORY_COMMITTED: () => ISo,
  METRIC_JVM_MEMORY_LIMIT: () => RSo,
  METRIC_JVM_MEMORY_USED: () => kSo,
  METRIC_JVM_MEMORY_USED_AFTER_LAST_GC: () => OSo,
  METRIC_JVM_THREAD_COUNT: () => NSo,
  METRIC_KESTREL_ACTIVE_CONNECTIONS: () => PSo,
  METRIC_KESTREL_ACTIVE_TLS_HANDSHAKES: () => BSo,
  METRIC_KESTREL_CONNECTION_DURATION: () => LSo,
  METRIC_KESTREL_QUEUED_CONNECTIONS: () => MSo,
  METRIC_KESTREL_QUEUED_REQUESTS: () => FSo,
  METRIC_KESTREL_REJECTED_CONNECTIONS: () => USo,
  METRIC_KESTREL_TLS_HANDSHAKE_DURATION: () => $So,
  METRIC_KESTREL_UPGRADED_CONNECTIONS: () => jSo,
  METRIC_SIGNALR_SERVER_ACTIVE_CONNECTIONS: () => QSo,
  METRIC_SIGNALR_SERVER_CONNECTION_DURATION: () => GSo,
  MessageTypeValues: () => t_o,
  MessagingDestinationKindValues: () => kyo,
  MessagingOperationValues: () => Pyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_CDMA: () => iyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_CDMA2000_1XRTT: () => ayo,
  NETHOSTCONNECTIONSUBTYPEVALUES_EDGE: () => ryo,
  NETHOSTCONNECTIONSUBTYPEVALUES_EHRPD: () => pyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_0: () => oyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_A: () => syo,
  NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_B: () => dyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_GPRS: () => tyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_GSM: () => gyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_HSDPA: () => uyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_HSPA: () => lyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_HSPAP: () => hyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_HSUPA: () => cyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_IDEN: () => myo,
  NETHOSTCONNECTIONSUBTYPEVALUES_IWLAN: () => Ayo,
  NETHOSTCONNECTIONSUBTYPEVALUES_LTE: () => fyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_LTE_CA: () => Eyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_NR: () => yyo,
  NETHOSTCONNECTIONSUBTYPEVALUES_NRNSA: () => _yo,
  NETHOSTCONNECTIONSUBTYPEVALUES_TD_SCDMA: () => byo,
  NETHOSTCONNECTIONSUBTYPEVALUES_UMTS: () => nyo,
  NETHOSTCONNECTIONTYPEVALUES_CELL: () => J6o,
  NETHOSTCONNECTIONTYPEVALUES_UNAVAILABLE: () => X6o,
  NETHOSTCONNECTIONTYPEVALUES_UNKNOWN: () => Z6o,
  NETHOSTCONNECTIONTYPEVALUES_WIFI: () => Y6o,
  NETHOSTCONNECTIONTYPEVALUES_WIRED: () => K6o,
  NETTRANSPORTVALUES_INPROC: () => V6o,
  NETTRANSPORTVALUES_IP: () => G6o,
  NETTRANSPORTVALUES_IP_TCP: () => j6o,
  NETTRANSPORTVALUES_IP_UDP: () => Q6o,
  NETTRANSPORTVALUES_OTHER: () => W6o,
  NETTRANSPORTVALUES_PIPE: () => H6o,
  NETTRANSPORTVALUES_UNIX: () => q6o,
  NETWORK_TRANSPORT_VALUE_PIPE: () => u4o,
  NETWORK_TRANSPORT_VALUE_QUIC: () => c4o,
  NETWORK_TRANSPORT_VALUE_TCP: () => C7u,
  NETWORK_TRANSPORT_VALUE_UDP: () => S7u,
  NETWORK_TRANSPORT_VALUE_UNIX: () => l4o,
  NETWORK_TYPE_VALUE_IPV4: () => d4o,
  NETWORK_TYPE_VALUE_IPV6: () => f4o,
  NetHostConnectionSubtypeValues: () => vyo,
  NetHostConnectionTypeValues: () => eyo,
  NetTransportValues: () => z6o,
  OSTYPEVALUES_AIX: () => Avo,
  OSTYPEVALUES_DARWIN: () => dvo,
  OSTYPEVALUES_DRAGONFLYBSD: () => gvo,
  OSTYPEVALUES_FREEBSD: () => fvo,
  OSTYPEVALUES_HPUX: () => bvo,
  OSTYPEVALUES_LINUX: () => mvo,
  OSTYPEVALUES_NETBSD: () => pvo,
  OSTYPEVALUES_OPENBSD: () => hvo,
  OSTYPEVALUES_SOLARIS: () => yvo,
  OSTYPEVALUES_WINDOWS: () => lvo,
  OSTYPEVALUES_Z_OS: () => _vo,
  OTEL_STATUS_CODE_VALUE_ERROR: () => b4o,
  OTEL_STATUS_CODE_VALUE_OK: () => w7u,
  OsTypeValues: () => Evo,
  RPCGRPCSTATUSCODEVALUES_ABORTED: () => Hyo,
  RPCGRPCSTATUSCODEVALUES_ALREADY_EXISTS: () => jyo,
  RPCGRPCSTATUSCODEVALUES_CANCELLED: () => Lyo,
  RPCGRPCSTATUSCODEVALUES_DATA_LOSS: () => Kyo,
  RPCGRPCSTATUSCODEVALUES_DEADLINE_EXCEEDED: () => Uyo,
  RPCGRPCSTATUSCODEVALUES_FAILED_PRECONDITION: () => qyo,
  RPCGRPCSTATUSCODEVALUES_INTERNAL: () => zyo,
  RPCGRPCSTATUSCODEVALUES_INVALID_ARGUMENT: () => Fyo,
  RPCGRPCSTATUSCODEVALUES_NOT_FOUND: () => $yo,
  RPCGRPCSTATUSCODEVALUES_OK: () => Byo,
  RPCGRPCSTATUSCODEVALUES_OUT_OF_RANGE: () => Vyo,
  RPCGRPCSTATUSCODEVALUES_PERMISSION_DENIED: () => Qyo,
  RPCGRPCSTATUSCODEVALUES_RESOURCE_EXHAUSTED: () => Gyo,
  RPCGRPCSTATUSCODEVALUES_UNAUTHENTICATED: () => Jyo,
  RPCGRPCSTATUSCODEVALUES_UNAVAILABLE: () => Yyo,
  RPCGRPCSTATUSCODEVALUES_UNIMPLEMENTED: () => Wyo,
  RPCGRPCSTATUSCODEVALUES_UNKNOWN: () => Myo,
  RpcGrpcStatusCodeValues: () => Xyo,
  SEMATTRS_AWS_DYNAMODB_ATTRIBUTES_TO_GET: () => I8o,
  SEMATTRS_AWS_DYNAMODB_ATTRIBUTE_DEFINITIONS: () => j8o,
  SEMATTRS_AWS_DYNAMODB_CONSISTENT_READ: () => x8o,
  SEMATTRS_AWS_DYNAMODB_CONSUMED_CAPACITY: () => v8o,
  SEMATTRS_AWS_DYNAMODB_COUNT: () => U8o,
  SEMATTRS_AWS_DYNAMODB_EXCLUSIVE_START_TABLE: () => P8o,
  SEMATTRS_AWS_DYNAMODB_GLOBAL_SECONDARY_INDEXES: () => O8o,
  SEMATTRS_AWS_DYNAMODB_GLOBAL_SECONDARY_INDEX_UPDATES: () => Q8o,
  SEMATTRS_AWS_DYNAMODB_INDEX_NAME: () => R8o,
  SEMATTRS_AWS_DYNAMODB_ITEM_COLLECTION_METRICS: () => C8o,
  SEMATTRS_AWS_DYNAMODB_LIMIT: () => D8o,
  SEMATTRS_AWS_DYNAMODB_LOCAL_SECONDARY_INDEXES: () => N8o,
  SEMATTRS_AWS_DYNAMODB_PROJECTION: () => T8o,
  SEMATTRS_AWS_DYNAMODB_PROVISIONED_READ_CAPACITY: () => S8o,
  SEMATTRS_AWS_DYNAMODB_PROVISIONED_WRITE_CAPACITY: () => w8o,
  SEMATTRS_AWS_DYNAMODB_SCANNED_COUNT: () => $8o,
  SEMATTRS_AWS_DYNAMODB_SCAN_FORWARD: () => L8o,
  SEMATTRS_AWS_DYNAMODB_SEGMENT: () => M8o,
  SEMATTRS_AWS_DYNAMODB_SELECT: () => k8o,
  SEMATTRS_AWS_DYNAMODB_TABLE_COUNT: () => B8o,
  SEMATTRS_AWS_DYNAMODB_TABLE_NAMES: () => E8o,
  SEMATTRS_AWS_DYNAMODB_TOTAL_SEGMENTS: () => F8o,
  SEMATTRS_AWS_LAMBDA_INVOKED_ARN: () => e5o,
  SEMATTRS_CODE_FILEPATH: () => i8o,
  SEMATTRS_CODE_FUNCTION: () => r8o,
  SEMATTRS_CODE_LINENO: () => o8o,
  SEMATTRS_CODE_NAMESPACE: () => n8o,
  SEMATTRS_DB_CASSANDRA_CONSISTENCY_LEVEL: () => m5o,
  SEMATTRS_DB_CASSANDRA_COORDINATOR_DC: () => g5o,
  SEMATTRS_DB_CASSANDRA_COORDINATOR_ID: () => h5o,
  SEMATTRS_DB_CASSANDRA_IDEMPOTENCE: () => f5o,
  SEMATTRS_DB_CASSANDRA_KEYSPACE: () => c5o,
  SEMATTRS_DB_CASSANDRA_PAGE_SIZE: () => l5o,
  SEMATTRS_DB_CASSANDRA_SPECULATIVE_EXECUTION_COUNT: () => p5o,
  SEMATTRS_DB_CASSANDRA_TABLE: () => d5o,
  SEMATTRS_DB_CONNECTION_STRING: () => r5o,
  SEMATTRS_DB_HBASE_NAMESPACE: () => b5o,
  SEMATTRS_DB_JDBC_DRIVER_CLASSNAME: () => i5o,
  SEMATTRS_DB_MONGODB_COLLECTION: () => y5o,
  SEMATTRS_DB_MSSQL_INSTANCE_NAME: () => u5o,
  SEMATTRS_DB_NAME: () => o5o,
  SEMATTRS_DB_OPERATION: () => a5o,
  SEMATTRS_DB_REDIS_DATABASE_INDEX: () => A5o,
  SEMATTRS_DB_SQL_TABLE: () => _5o,
  SEMATTRS_DB_STATEMENT: () => s5o,
  SEMATTRS_DB_SYSTEM: () => t5o,
  SEMATTRS_DB_USER: () => n5o,
  SEMATTRS_ENDUSER_ID: () => J5o,
  SEMATTRS_ENDUSER_ROLE: () => X5o,
  SEMATTRS_ENDUSER_SCOPE: () => Z5o,
  SEMATTRS_EXCEPTION_ESCAPED: () => S5o,
  SEMATTRS_EXCEPTION_MESSAGE: () => v5o,
  SEMATTRS_EXCEPTION_STACKTRACE: () => C5o,
  SEMATTRS_EXCEPTION_TYPE: () => E5o,
  SEMATTRS_FAAS_COLDSTART: () => N5o,
  SEMATTRS_FAAS_CRON: () => O5o,
  SEMATTRS_FAAS_DOCUMENT_COLLECTION: () => T5o,
  SEMATTRS_FAAS_DOCUMENT_NAME: () => R5o,
  SEMATTRS_FAAS_DOCUMENT_OPERATION: () => D5o,
  SEMATTRS_FAAS_DOCUMENT_TIME: () => I5o,
  SEMATTRS_FAAS_EXECUTION: () => x5o,
  SEMATTRS_FAAS_INVOKED_NAME: () => P5o,
  SEMATTRS_FAAS_INVOKED_PROVIDER: () => B5o,
  SEMATTRS_FAAS_INVOKED_REGION: () => L5o,
  SEMATTRS_FAAS_TIME: () => k5o,
  SEMATTRS_FAAS_TRIGGER: () => w5o,
  SEMATTRS_HTTP_CLIENT_IP: () => _8o,
  SEMATTRS_HTTP_FLAVOR: () => d8o,
  SEMATTRS_HTTP_HOST: () => c8o,
  SEMATTRS_HTTP_METHOD: () => s8o,
  SEMATTRS_HTTP_REQUEST_CONTENT_LENGTH: () => p8o,
  SEMATTRS_HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED: () => h8o,
  SEMATTRS_HTTP_RESPONSE_CONTENT_LENGTH: () => g8o,
  SEMATTRS_HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED: () => b8o,
  SEMATTRS_HTTP_ROUTE: () => y8o,
  SEMATTRS_HTTP_SCHEME: () => l8o,
  SEMATTRS_HTTP_SERVER_NAME: () => A8o,
  SEMATTRS_HTTP_STATUS_CODE: () => m8o,
  SEMATTRS_HTTP_TARGET: () => u8o,
  SEMATTRS_HTTP_URL: () => a8o,
  SEMATTRS_HTTP_USER_AGENT: () => f8o,
  SEMATTRS_MESSAGE_COMPRESSED_SIZE: () => A9o,
  SEMATTRS_MESSAGE_ID: () => b9o,
  SEMATTRS_MESSAGE_TYPE: () => g9o,
  SEMATTRS_MESSAGE_UNCOMPRESSED_SIZE: () => y9o,
  SEMATTRS_MESSAGING_CONSUMER_ID: () => t9o,
  SEMATTRS_MESSAGING_CONVERSATION_ID: () => J8o,
  SEMATTRS_MESSAGING_DESTINATION: () => q8o,
  SEMATTRS_MESSAGING_DESTINATION_KIND: () => H8o,
  SEMATTRS_MESSAGING_KAFKA_CLIENT_ID: () => o9o,
  SEMATTRS_MESSAGING_KAFKA_CONSUMER_GROUP: () => i9o,
  SEMATTRS_MESSAGING_KAFKA_MESSAGE_KEY: () => n9o,
  SEMATTRS_MESSAGING_KAFKA_PARTITION: () => s9o,
  SEMATTRS_MESSAGING_KAFKA_TOMBSTONE: () => a9o,
  SEMATTRS_MESSAGING_MESSAGE_ID: () => K8o,
  SEMATTRS_MESSAGING_MESSAGE_PAYLOAD_COMPRESSED_SIZE_BYTES: () => Z8o,
  SEMATTRS_MESSAGING_MESSAGE_PAYLOAD_SIZE_BYTES: () => X8o,
  SEMATTRS_MESSAGING_OPERATION: () => e9o,
  SEMATTRS_MESSAGING_PROTOCOL: () => W8o,
  SEMATTRS_MESSAGING_PROTOCOL_VERSION: () => z8o,
  SEMATTRS_MESSAGING_RABBITMQ_ROUTING_KEY: () => r9o,
  SEMATTRS_MESSAGING_SYSTEM: () => G8o,
  SEMATTRS_MESSAGING_TEMP_DESTINATION: () => V8o,
  SEMATTRS_MESSAGING_URL: () => Y8o,
  SEMATTRS_NET_HOST_CARRIER_ICC: () => Y5o,
  SEMATTRS_NET_HOST_CARRIER_MCC: () => W5o,
  SEMATTRS_NET_HOST_CARRIER_MNC: () => z5o,
  SEMATTRS_NET_HOST_CARRIER_NAME: () => V5o,
  SEMATTRS_NET_HOST_CONNECTION_SUBTYPE: () => H5o,
  SEMATTRS_NET_HOST_CONNECTION_TYPE: () => q5o,
  SEMATTRS_NET_HOST_IP: () => j5o,
  SEMATTRS_NET_HOST_NAME: () => G5o,
  SEMATTRS_NET_HOST_PORT: () => Q5o,
  SEMATTRS_NET_PEER_IP: () => F5o,
  SEMATTRS_NET_PEER_NAME: () => $5o,
  SEMATTRS_NET_PEER_PORT: () => U5o,
  SEMATTRS_NET_TRANSPORT: () => M5o,
  SEMATTRS_PEER_SERVICE: () => K5o,
  SEMATTRS_RPC_GRPC_STATUS_CODE: () => m9o,
  SEMATTRS_RPC_JSONRPC_ERROR_CODE: () => p9o,
  SEMATTRS_RPC_JSONRPC_ERROR_MESSAGE: () => h9o,
  SEMATTRS_RPC_JSONRPC_REQUEST_ID: () => f9o,
  SEMATTRS_RPC_JSONRPC_VERSION: () => d9o,
  SEMATTRS_RPC_METHOD: () => l9o,
  SEMATTRS_RPC_SERVICE: () => c9o,
  SEMATTRS_RPC_SYSTEM: () => u9o,
  SEMATTRS_THREAD_ID: () => e8o,
  SEMATTRS_THREAD_NAME: () => t8o,
  SEMRESATTRS_AWS_ECS_CLUSTER_ARN: () => u_o,
  SEMRESATTRS_AWS_ECS_CONTAINER_ARN: () => a_o,
  SEMRESATTRS_AWS_ECS_LAUNCHTYPE: () => c_o,
  SEMRESATTRS_AWS_ECS_TASK_ARN: () => l_o,
  SEMRESATTRS_AWS_ECS_TASK_FAMILY: () => m_o,
  SEMRESATTRS_AWS_ECS_TASK_REVISION: () => d_o,
  SEMRESATTRS_AWS_EKS_CLUSTER_ARN: () => f_o,
  SEMRESATTRS_AWS_LOG_GROUP_ARNS: () => h_o,
  SEMRESATTRS_AWS_LOG_GROUP_NAMES: () => p_o,
  SEMRESATTRS_AWS_LOG_STREAM_ARNS: () => b_o,
  SEMRESATTRS_AWS_LOG_STREAM_NAMES: () => g_o,
  SEMRESATTRS_CLOUD_ACCOUNT_ID: () => n_o,
  SEMRESATTRS_CLOUD_AVAILABILITY_ZONE: () => o_o,
  SEMRESATTRS_CLOUD_PLATFORM: () => s_o,
  SEMRESATTRS_CLOUD_PROVIDER: () => r_o,
  SEMRESATTRS_CLOUD_REGION: () => i_o,
  SEMRESATTRS_CONTAINER_ID: () => y_o,
  SEMRESATTRS_CONTAINER_IMAGE_NAME: () => E_o,
  SEMRESATTRS_CONTAINER_IMAGE_TAG: () => v_o,
  SEMRESATTRS_CONTAINER_NAME: () => A_o,
  SEMRESATTRS_CONTAINER_RUNTIME: () => __o,
  SEMRESATTRS_DEPLOYMENT_ENVIRONMENT: () => C_o,
  SEMRESATTRS_DEVICE_ID: () => S_o,
  SEMRESATTRS_DEVICE_MODEL_IDENTIFIER: () => w_o,
  SEMRESATTRS_DEVICE_MODEL_NAME: () => x_o,
  SEMRESATTRS_FAAS_ID: () => D_o,
  SEMRESATTRS_FAAS_INSTANCE: () => R_o,
  SEMRESATTRS_FAAS_MAX_MEMORY: () => k_o,
  SEMRESATTRS_FAAS_NAME: () => T_o,
  SEMRESATTRS_FAAS_VERSION: () => I_o,
  SEMRESATTRS_HOST_ARCH: () => B_o,
  SEMRESATTRS_HOST_ID: () => O_o,
  SEMRESATTRS_HOST_IMAGE_ID: () => M_o,
  SEMRESATTRS_HOST_IMAGE_NAME: () => L_o,
  SEMRESATTRS_HOST_IMAGE_VERSION: () => F_o,
  SEMRESATTRS_HOST_NAME: () => N_o,
  SEMRESATTRS_HOST_TYPE: () => P_o,
  SEMRESATTRS_K8S_CLUSTER_NAME: () => U_o,
  SEMRESATTRS_K8S_CONTAINER_NAME: () => H_o,
  SEMRESATTRS_K8S_CRONJOB_NAME: () => nEo,
  SEMRESATTRS_K8S_CRONJOB_UID: () => rEo,
  SEMRESATTRS_K8S_DAEMONSET_NAME: () => Z_o,
  SEMRESATTRS_K8S_DAEMONSET_UID: () => X_o,
  SEMRESATTRS_K8S_DEPLOYMENT_NAME: () => Y_o,
  SEMRESATTRS_K8S_DEPLOYMENT_UID: () => z_o,
  SEMRESATTRS_K8S_JOB_NAME: () => tEo,
  SEMRESATTRS_K8S_JOB_UID: () => eEo,
  SEMRESATTRS_K8S_NAMESPACE_NAME: () => Q_o,
  SEMRESATTRS_K8S_NODE_NAME: () => $_o,
  SEMRESATTRS_K8S_NODE_UID: () => j_o,
  SEMRESATTRS_K8S_POD_NAME: () => q_o,
  SEMRESATTRS_K8S_POD_UID: () => G_o,
  SEMRESATTRS_K8S_REPLICASET_NAME: () => W_o,
  SEMRESATTRS_K8S_REPLICASET_UID: () => V_o,
  SEMRESATTRS_K8S_STATEFULSET_NAME: () => J_o,
  SEMRESATTRS_K8S_STATEFULSET_UID: () => K_o,
  SEMRESATTRS_OS_DESCRIPTION: () => oEo,
  SEMRESATTRS_OS_NAME: () => sEo,
  SEMRESATTRS_OS_TYPE: () => iEo,
  SEMRESATTRS_OS_VERSION: () => aEo,
  SEMRESATTRS_PROCESS_COMMAND: () => mEo,
  SEMRESATTRS_PROCESS_COMMAND_ARGS: () => fEo,
  SEMRESATTRS_PROCESS_COMMAND_LINE: () => dEo,
  SEMRESATTRS_PROCESS_EXECUTABLE_NAME: () => cEo,
  SEMRESATTRS_PROCESS_EXECUTABLE_PATH: () => lEo,
  SEMRESATTRS_PROCESS_OWNER: () => pEo,
  SEMRESATTRS_PROCESS_PID: () => uEo,
  SEMRESATTRS_PROCESS_RUNTIME_DESCRIPTION: () => bEo,
  SEMRESATTRS_PROCESS_RUNTIME_NAME: () => hEo,
  SEMRESATTRS_PROCESS_RUNTIME_VERSION: () => gEo,
  SEMRESATTRS_SERVICE_INSTANCE_ID: () => _Eo,
  SEMRESATTRS_SERVICE_NAME: () => AEo,
  SEMRESATTRS_SERVICE_NAMESPACE: () => yEo,
  SEMRESATTRS_SERVICE_VERSION: () => EEo,
  SEMRESATTRS_TELEMETRY_AUTO_VERSION: () => wEo,
  SEMRESATTRS_TELEMETRY_SDK_LANGUAGE: () => CEo,
  SEMRESATTRS_TELEMETRY_SDK_NAME: () => vEo,
  SEMRESATTRS_TELEMETRY_SDK_VERSION: () => SEo,
  SEMRESATTRS_WEBENGINE_DESCRIPTION: () => DEo,
  SEMRESATTRS_WEBENGINE_NAME: () => xEo,
  SEMRESATTRS_WEBENGINE_VERSION: () => TEo,
  SIGNALR_CONNECTION_STATUS_VALUE_APP_SHUTDOWN: () => v4o,
  SIGNALR_CONNECTION_STATUS_VALUE_NORMAL_CLOSURE: () => C4o,
  SIGNALR_CONNECTION_STATUS_VALUE_TIMEOUT: () => S4o,
  SIGNALR_TRANSPORT_VALUE_LONG_POLLING: () => x4o,
  SIGNALR_TRANSPORT_VALUE_SERVER_SENT_EVENTS: () => T4o,
  SIGNALR_TRANSPORT_VALUE_WEB_SOCKETS: () => D4o,
  SemanticAttributes: () => Cte,
  SemanticResourceAttributes: () => IEo,
  TELEMETRYSDKLANGUAGEVALUES_CPP: () => vvo,
  TELEMETRYSDKLANGUAGEVALUES_DOTNET: () => Cvo,
  TELEMETRYSDKLANGUAGEVALUES_ERLANG: () => Svo,
  TELEMETRYSDKLANGUAGEVALUES_GO: () => wvo,
  TELEMETRYSDKLANGUAGEVALUES_JAVA: () => xvo,
  TELEMETRYSDKLANGUAGEVALUES_NODEJS: () => Tvo,
  TELEMETRYSDKLANGUAGEVALUES_PHP: () => Dvo,
  TELEMETRYSDKLANGUAGEVALUES_PYTHON: () => Ivo,
  TELEMETRYSDKLANGUAGEVALUES_RUBY: () => Rvo,
  TELEMETRYSDKLANGUAGEVALUES_WEBJS: () => kvo,
  TELEMETRY_SDK_LANGUAGE_VALUE_CPP: () => x7u,
  TELEMETRY_SDK_LANGUAGE_VALUE_DOTNET: () => R4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_ERLANG: () => k4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_GO: () => T7u,
  TELEMETRY_SDK_LANGUAGE_VALUE_JAVA: () => O4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_NODEJS: () => N4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_PHP: () => D7u,
  TELEMETRY_SDK_LANGUAGE_VALUE_PYTHON: () => P4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_RUBY: () => B4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_RUST: () => L4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_SWIFT: () => M4o,
  TELEMETRY_SDK_LANGUAGE_VALUE_WEBJS: () => F4o,
  TelemetrySdkLanguageValues: () => Ovo,
});
var $1 = j(() => {
  pjr();
  $Gr();
  jGr();
  QGr();
  GGr();
});